#киборг-охранник
- type: entity
  id: BorgChassisSecurity
  parent: BorgChassisSelectable
  name: киборг-охранник
  components:
  - type: FlashImmunity
  - type: BorgCuffed
  - type: BorgSwitchableType
    selectedBorgType: security
  - type: PointLight
    color: "#97fcef"

- type: borgType
  id: security

  dummyPrototype: BorgChassisSecurity

  extraModuleCount: 3
  moduleWhitelist:
    tags:
    - BorgModuleGeneric
    - SecModul

  defaultModules:
  - BorgModuleTool
  - ModuleSec

  radioChannels:
  - Security
  - Science

  inventoryTemplateId: borgShort
  spriteBodyState: sec
  spriteHasMindState: sec_e
  spriteNoMindState: sec_e_r
  spriteToggleLightState: sec_l

  petSuccessString: petting-success-engineer-cyborg
  petFailureString: petting-failure-engineer-cyborg

