# Best job.

- type: job
  id: ChiefMedicalOfficer
  name: job-name-cmo
  description: job-description-cmo
  playTimeTracker: JobChiefMedicalOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 14400 #4 hrs # Adventure
#    - !type:RoleTimeRequirement
#      role: JobMedicalDoctor
#      time: 21600 #6 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 54000 #15 hrs # Adventure
    - !type:AgeRequirement
      requiredAge: 30 # Adventure
# Adventure-edit-start
    - !type:SpeciesRequirement
      inverted: true
      species:
      - Synth
      - Zerah
      - PigMan
      - Vox
# Adventure-edit-end
  startingGear: CMOGear
  icon: "JobIconChiefMedicalOfficer"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CMOGear
  equipment:
    id: CMOPDA
    ears: ClothingHeadsetCMO
    belt: ClothingBeltMedicalFilled
    ipc: IPCModulMed # Adventure-IPC
  storage:
    back:
    - Flash
