#Роль
- type: job
  id: SOO
  name: Офицер Специальных Операций
  description: Защищайте активы НаноТрейзен.
  playTimeTracker: JobBlueshield
# Adventure-edit-end
  startingGear: BlueshieldGear
  icon: "JobIconSOO"
  requireAdminNotify: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial

  #Иконка
- type: jobIcon
  parent: JobIcon
  id: JobIconSOO
  icon:
    sprite: _Adventure/Roles/SOO/misc/SOO_icon.rsi
    state: BlueShieldOfficer
  jobName: Офицер Специальных Операций

#Комбинезон ОСО
- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitSOO
  name: комбинезон ОСО
  description: Чёрный тактический комбинезон с армированными вставками, готов к любому сценарию.
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SOO/SOO_Uniform.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SOO/SOO_Uniform.rsi

#Фуражка ОСО
- type: entity
  parent: ClothingHeadBase
  id: ClothingHeadCapSOO
  name: Фуражка ОСО
  description: Фуражка Офицера Спецопераций. Символ власти — и прицел для врагов.
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SOO/SOO_Cap.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SOO/SOO_Cap.rsi

#Гарнитура-наушники ОСО
- type: entity
  name: гарнитура-наушники ОСО
  parent: ClothingHeadsetAltCentCom
  id: SOOHeadsetAlt
  description: Тактическая гарнитура. Говори тихо — тебя и так слышат.
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SOO/SOO_HeadSet.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SOO/SOO_HeadSet.rsi

#Очки ОСО
- type: entity
  parent: [ClothingEyesGlassesSunglasses, ShowSecurityIcons, ShowMedicalIcons]
  id: ClothingEyesGlassesSOO
  description: Они не скрывают лицо. Но скрывают взгляд.
  name: очки ОСО
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SOO/SOO_Glasses.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SOO/SOO_Glasses.rsi
  - type: FlashImmunity
  - type: EyeProtection
    protectionTime: 5

#Перчатки ОСО
- type: entity
  parent: ClothingHandsGlovesCaptain
  id: ClothingHandsGlovesSOO
  name: перчатки ОСО
  description: Не просто перчатки. Это подпись на каждом трупе.
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SOO/SOO_Gloves.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SOO/SOO_Gloves.rsi

#Противогаз ОСО
- type: entity
  parent: ClothingMaskGas
  id: ClothingMaskSOO
  name: противогаз ОСО
  description: Не освежает дыхание.
  components:
  - type: Item
    size: Tiny
  - type: Sprite
    sprite: _Adventure/Roles/SOO/SOO_Mask.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SOO/SOO_Mask.rsi
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.90
        Slash: 0.90
        Piercing: 0.90
        Heat: 0.90
  - type: IngestionBlocker
  - type: IdentityBlocker
  - type: Tag
  - type: FlashImmunity
  - type: EyeProtection
    protectionTime: 5

#Трэнч ОСО
- type: entity
  parent: ClothingOuterArmorBasic
  id: SOOArmoredTrench
  name: укреплённый тренч офицера синий щит
  description: На внутренней подкладке — схема станции. Последняя метка — там, где ещё никто не умер… но скоро умрёт.
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SOO/SOO_Trench.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SOO/SOO_Trench.rsi
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.60
        Slash: 0.60
        Piercing: 0.50
        Heat: 0.70
  - type: ExplosionResistance
    damageCoefficient: 0.75

#Рюкзак ОСО
- type: entity
  parent: ClothingBackpackDeathSquad
  id: ClothingMilitaryBackpackSOO
  name: рюкзак ОСО
  description: Тактический ранец. Всё необходимое — под рукой. Даже то, о чём ты не должен знать.
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SOO/SOO_BackPack.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SOO/SOO_BackPack.rsi
  - type: StorageFill
    contents:
    - id: BoxZiptie
    - id: CrowbarRed
    - id: DoubleEmergencyOxygenTankFilled

#ID карта ОСО
- type: entity
  parent: IDCardStandard
  id: SOOIDCard
  name: ID карта ОСО
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SOO/misc/SOO_IDcard.rsi
    layers:
    - state: idSOO
  - type: PresetIdCard
    job: SOO
  - type: Item
    heldPrefix: idSOO

#КПК ОСО
- type: entity
  parent: BasePDA
  id: SOOPDA
  name: КПК ОСО
  description: Подключён ко всему. Даже к тому, что не должно существовать.
  components:
  - type: Pda
    id: SOOIDCard
  - type: Appearance
    appearanceDataInit:
     enum.PdaVisuals.PdaType:
       !type:String
       pda-SOO
  - type: PdaBorderColor
    borderColor: "#383838"
    accentVColor: "#383838"
  - type: Icon
    state: pda-SOO
    
#Скафандр ОСО
- type: entity
  parent: ClothingOuterHardsuitSecurity
  id: ClothingOuterHardsuitSOO
  name: скафандр ОСО
  description: Последний скафандр, который ты наденешь. Потому что следующий — уже не потребуется.
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SOO/SOO_hardhuit/SOO_hardhuit.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SOO/SOO_hardhuit/SOO_hardhuit.rsi
  - type: PressureProtection
    highPressureMultiplier: 0.5
    lowPressureMultiplier: 1000
  - type: ExplosionResistance
    damageCoefficient: 0.7
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.30
        Slash: 0.30
        Piercing: 0.30
        Caustic: 0.30
  - type: ClothingSpeedModifier
    walkModifier: 0.85
    sprintModifier: 0.85
  - type: HeldSpeedModifier
  - type: ToggleableClothing
    clothingPrototype: ClothingHeadHelmetHardsuitSOO

- type: entity
  parent: ClothingHeadHardsuitBase
  id: ClothingHeadHelmetHardsuitSOO
  name: шлем скафандра ОСО
  description: Голос в наушнике — не твой. И не командования. Он всегда был здесь.
  components:
  - type: BreathMask
  - type: Sprite
    sprite: _Adventure/Roles/SOO/SOO_hardhuit/SOO_hardhuit_helmet.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SOO/SOO_hardhuit/SOO_hardhuit_helmet.rsi
  - type: PressureProtection
    highPressureMultiplier: 0.3
    lowPressureMultiplier: 1000
