- type: localizedDataset
  id: NamesFirst
  values:
    prefix: names-first-dataset-
    count: 1395 # adventure localization

- type: localizedDataset
  id: NamesLast
  values:
    prefix: names-last-dataset-
    count: 553 # adventure localization
