- type: localizedDataset
  id: NamesFirst
  values:
    prefix: names-first-dataset-
    count: 809 # adventure localization

- type: localizedDataset
  id: NamesLast
  values:
    prefix: names-last-dataset-
    count: 503 # adventure localization
