# Аплинк солдата
- type: entity
  parent: BaseItem
  id: Cburnuplink
  name: терминал РХБЗЗ
  suffix: Adventure
  description: Терминал который используют оперативники РХБЗЗ в специальных операциях.
  components:
  - type: Item
    size: Small
    sprite: _Adventure/Roles/SpecialForces/Uplinks/communication.rsi
  - type: UserInterface
    interfaces:
      enum.StoreUiKey.Key:
        type: StoreBoundUserInterface
  - type: ActivatableUI
    key: enum.StoreUiKey.Key
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/Uplinks/communication.rsi
    layers:
    - state: CBURN
  - type: Appearance
  - type: StaticPrice
    price: 100
  - type: Store
    categories:
      - CBURNweapons # оружие
      - CBURNammo # боеприпасы
      - CBURNmore # снаряжение
      - CBURNbombs # Взрывчатка
      - CBURNmedicine # В медицина
    currencyWhitelist:
      - CentCommCrystal
    balance:
      CentCommCrystal: 45

# Аплинк Офицера
- type: entity
  parent: BaseItem
  id: Cburnuplinkleader
  name: терминал командира РХБЗЗ
  suffix: Adventure
  description: Терминал который используют командиры РХБЗЗ в специальных операциях.
  components:
  - type: Item
    size: Small
    sprite: _Adventure/Roles/SpecialForces/Uplinks/communication.rsi
  - type: UserInterface
    interfaces:
      enum.StoreUiKey.Key:
        type: StoreBoundUserInterface
  - type: ActivatableUI
    key: enum.StoreUiKey.Key
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/Uplinks/communication.rsi
    layers:
    - state: CBURN_L
  - type: Appearance
  - type: StaticPrice
    price: 100
  - type: Store
    categories:
      - CBURNleader # каталог лидера
      - CBURNweapons # оружие
      - CBURNammo # боеприпасы
      - CBURNmore # снаряжение
      - CBURNbombs # Взрывчатка
      - CBURNmedicine # В медицина
    currencyWhitelist:
      - CentCommCrystal
    balance:
      CentCommCrystal: 55

# Предметы аплинка - Оружие
- type: storeCategory
  id: CBURNweapons
  name: Оружие

- type: listing
  id: WeaponPistolMk58CBURN
  productEntity: WeaponPistolMk58
  cost:
    CentCommCrystal: 2
  categories:
  - CBURNweapons

- type: listing
  id: WeaponDisablerCBURN
  productEntity: WeaponDisabler
  cost:
    CentCommCrystal: 3
  categories:
  - CBURNweapons

- type: listing
  id: WeaponLaserGunCBURN
  productEntity: WeaponLaserGun
  cost:
    CentCommCrystal: 7
  categories:
  - CBURNweapons

- type: listing
  id: WeaponLaserCarbineCBURN
  productEntity: WeaponLaserCarbine
  cost:
    CentCommCrystal: 10
  categories:
  - CBURNweapons

- type: listing
  id: WeaponShotgunKammererCBURN
  productEntity: WeaponShotgunKammerer
  cost:
    CentCommCrystal: 12
  categories:
  - CBURNweapons

- type: listing
  id: WeaponRifleLecterCBURN
  productEntity: WeaponRifleLecter
  cost:
    CentCommCrystal: 15
  categories:
  - CBURNweapons

- type: listing
  id: WeaponShotgunEnforcerCBURN
  productEntity: WeaponShotgunEnforcer
  cost:
    CentCommCrystal: 17
  categories:
  - CBURNweapons

- type: listing
  id: WeaponLaserCannonCBURN
  productEntity: WeaponLaserCannon
  cost:
    CentCommCrystal: 17
  categories:
  - CBURNweapons

- type: listing
  id: FirethrowerGunCBURN
  description: Топливный бак в комплект не входит.
  productEntity: FirethrowerGun
  cost:
    CentCommCrystal: 17
  categories:
  - CBURNweapons

- type: listing
  id: WeaponPulseCarbineCBURN
  productEntity: WeaponPulseCarbine
  cost:
    CentCommCrystal: 19
  categories:
  - CBURNweapons
# /Предметы аплинка - Оружие

# Предметы аплинка - Патроны
- type: storeCategory
  id: CBURNammo
  name: Боеприпасы

- type: listing
  id: MagazinePistolCBURN
  description: Магазин калибра .35 авто. Подходящий для простых пистолетов
  productEntity: MagazinePistol
  cost:
    CentCommCrystal: 1
  categories:
  - CBURNammo

- type: listing
  id: MagazinePistolSubMachineGunTopMountedCBURN
  description: Надствольный магазин калибра .35 авто. Подходящий для пистолетов-пулемётов.
  productEntity: MagazinePistolSubMachineGunTopMounted
  cost:
    CentCommCrystal: 2
  categories:
  - CBURNammo

- type: listing
  id: MagazineBoxPistolCBURN
  description: Коробка калибра .35 авто. Подходящий для простых пистолетов.
  productEntity: MagazineBoxPistol
  cost:
    CentCommCrystal: 3
  categories:
  - CBURNammo

- type: listing
  id: MagazineShotgunCBURN
  description: Барабан калибра .50. Подходящий дробовиков.
  productEntity: MagazineShotgun
  cost:
    CentCommCrystal: 3
  categories:
  - CBURNammo

- type: listing
  id: FuelTankFirethrowerCBURN
  description: Топливный бак для огнемёта. Надеюсь вы не забыли надеть его на спину.
  productEntity: FuelTankFirethrower
  cost:
    CentCommCrystal: 3
  categories:
  - CBURNammo

- type: listing
  id: MagazineShotgunIncendiaryCBURN
  description: Зажигательный барабан калибра .50. Подходящий дробовиков.
  productEntity: MagazineShotgunIncendiary
  cost:
    CentCommCrystal: 5
  categories:
  - CBURNammo

- type: listing
  id: MagazineRifleCBURN
  description: Магазин калибра .20 винтовочный. Подходящий для автоматов.
  productEntity: MagazineRifle
  cost:
    CentCommCrystal: 2
  categories:
  - CBURNammo
# /Предметы аплинка - Патроны


# Предметы аплинка - Разное
- type: storeCategory
  id: CBURNmore
  name: Разное

- type: listing
  id: MindShieldImplanterCBURN
  description: Имплант для защиты от промывки мозгов.
  productEntity: MindShieldImplanter
  cost:
    CentCommCrystal: 1
  categories:
  - CBURNmore

- type: listing
  id: ClothingBeltMilitaryWebbingCBURN
  productEntity: ClothingBeltMilitaryWebbing
  cost:
    CentCommCrystal: 1
  categories:
  - CBURNmore

- type: listing
  id: ClothingShoesBootsMagCBURN
  productEntity: ClothingShoesBootsMag
  cost:
    CentCommCrystal: 3
  categories:
  - CBURNmore

- type: listing
  id: JetpackBlueFilledCBURN
  productEntity: JetpackBlueFilled
  cost:
    CentCommCrystal: 3
  categories:
  - CBURNmore

- type: listing
  id: ClothingOuterHardsuitCBURNCBURN
  productEntity: ClothingOuterHardsuitCBURN
  cost:
    CentCommCrystal: 5
  categories:
  - CBURNmore

- type: listing
  id: JawsOfLifeCBURN
  productEntity: JawsOfLife
  cost:
    CentCommCrystal: 5
  categories:
  - CBURNmore

# /Предметы аплинка - Разное

# Предметы аплинка - Взрывчатка
- type: storeCategory
  id: CBURNbombs
  name: Взрывчатка

- type: listing
  id: GrenadeFlashBangCBURN
  productEntity: GrenadeFlashBang
  cost:
    CentCommCrystal: 1
  categories:
  - CBURNbombs

- type: listing
  id: ClusterBangFullCBURN
  productEntity: ClusterBangFull
  cost:
    CentCommCrystal: 2
  categories:
  - CBURNbombs

- type: listing
  id: GrenadeIncendiaryCBURN
  productEntity: GrenadeIncendiary
  cost:
    CentCommCrystal: 3
  categories:
  - CBURNbombs

- type: listing
  id: ExGrenadeCBURN
  productEntity: ExGrenade
  cost:
    CentCommCrystal: 3
  categories:
  - CBURNbombs

- type: listing
  id: ClusterGrenadeCBURN
  productEntity: ClusterGrenade
  cost:
    CentCommCrystal: 7
  categories:
  - CBURNbombs
# /Предметы аплинка - Взрывчатка

# Предметы аплинка - Медицина
- type: listing
  id: BrutepackCBURN
  productEntity: Brutepack
  cost:
    CentCommCrystal: 1
  categories:
  - CBURNmedicine

- type: storeCategory
  id: CBURNmedicine
  name: Медицина

- type: listing
  id: OintmentCBURN
  productEntity: Ointment
  cost:
    CentCommCrystal: 1
  categories:
  - CBURNmedicine

- type: listing
  id: MaterialBiomassCBURN
  productEntity: MaterialBiomass
  cost:
    CentCommCrystal: 1
  categories:
  - CBURNmedicine

- type: listing
  id: HandheldHealthAnalyzerCBURN
  productEntity: HandheldHealthAnalyzer
  cost:
    CentCommCrystal: 1
  categories:
  - CBURNmedicine

- type: listing
  id: BloodpackCBURN
  productEntity: Bloodpack
  cost:
    CentCommCrystal: 1
  categories:
  - CBURNmedicine

- type: listing
  id: MedicatedSutureCBURN
  productEntity: MedicatedSuture
  cost:
    CentCommCrystal: 3
  categories:
  - CBURNmedicine

- type: listing
  id: RegenerativeMeshCBURN
  productEntity: RegenerativeMesh
  cost:
    CentCommCrystal: 3
  categories:
  - CBURNmedicine

- type: listing
  id: MedkitAdvancedFilledCBURN
  productEntity: MedkitAdvancedFilled
  cost:
    CentCommCrystal: 6
  categories:
  - CBURNmedicine

- type: listing
  id: MedkitCombatFilledCBURN
  productEntity: MedkitCombatFilled
  cost:
    CentCommCrystal: 6
  categories:
  - CBURNmedicine

- type: listing
  id: InjectorMediumNanitsCBURN
  productEntity: InjectorMediumNanits
  cost:
    CentCommCrystal: 15
  categories:
  - CBURNmedicine
  conditions:
    - !type:ListingLimitedStockCondition
     stock: 1

# /Предметы аплинка - Медицина

# Предметы аплинка - Лидер
- type: storeCategory
  id: CBURNleader
  name: Лидер РХБЗЗ

- type: listing
  id: ClothingShoesBootsMagAdvCBURN
  description: Кто сказал, что лидер отряда должен носить обычные магнитные ботинки?
  productEntity: ClothingShoesBootsMagAdv
  cost:
    CentCommCrystal: 5
  categories:
  - CBURNleader
  conditions:
    - !type:ListingLimitedStockCondition
     stock: 1

- type: listing
  id: WeaponRifleAkCBURN
  description: Настоящий автомат, настоящего офицера.
  productEntity: WeaponRifleAk
  cost:
    CentCommCrystal: 15
  categories:
  - CBURNleader
  conditions:
    - !type:ListingLimitedStockCondition
     stock: 1

- type: listing
  id: MagazineLightRifleCBURN
  description: Магазин калибра .30 винтовочный. Подходящий для АКМС.
  productEntity: MagazineLightRifle
  cost:
    CentCommCrystal: 2
  categories:
  - CBURNleader

- type: listing
  id: MagazineBoxLightRifleBigCBURN
  description: Коробка патронов калибра .30 винтовочный. Подходящих для АКМС.
  productEntity: MagazineBoxLightRifleBig
  cost:
    CentCommCrystal: 6
  categories:
  - CBURNleader

# /Предметы аплинка - Лидер
