- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 20h # Adventure
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 10h # Adventure
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 10h # Adventure
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 10h # Adventure
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 10h # Adventure
    - !type:DepartmentTimeRequirement
      department: Science
      time: 10h # Adventure
    - !type:DepartmentTimeRequirement
      department: Security
      time: 15h # Adventure
    - !type:DepartmentTimeRequirement
      department: Command
      time: 10h # Adventure
    - !type:AgeRequirement
      requiredAge: 21 # Adventure
# Adventure-edit-start
    - !type:SpeciesRequirement
      inverted: true
      species:
      - Synth
      - Zerah
      - PigMan
      - Vox
      - PlasMan
      - InsectSerpentide
# Adventure-edit-end
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CaptainGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesCommand
    gloves: ClothingHandsGlovesCaptain
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
    ipc: IPCModulCommand # Adventure-IPC
  storage:
    back:
    - Flash
    # - StationCharter

- type: chameleonOutfit
  id: CaptainChameleonOutfit
  job: Captain
  hasMindShield: true
  equipment:
    head: ClothingHeadHatCapcap
    eyes: ClothingEyesGlassesCommand
    mask: ClothingMaskGasCaptain
    neck: ClothingNeckCloakCap
