- type: job
  id: HeadOfPersonnel
  name: job-name-hop
  description: job-description-hop
  playTimeTracker: JobHeadOfPersonnel
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 15h # Adventure
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 5h # Adventure
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 5h # Adventure
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 5h # Adventure
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 5h # Adventure
    - !type:DepartmentTimeRequirement
      department: Science
      time: 5h # Adventure
    - !type:DepartmentTimeRequirement
      department: Security
      time: 5h # Adventure
    - !type:DepartmentTimeRequirement
      department: Command
      time: 5h # Adventure
    - !type:AgeRequirement
      requiredAge: 21 # Adventure
# Adventure-edit-start
    - !type:SpeciesRequirement
      inverted: true
      species:
      - Synth
      - Zerah
      - PigMan
      - Vox
      - PlasMan
      - InsectSerpentide
      - Xiod
# Adventure-edit-end
  weight: 20
  startingGear: HoPGear
  icon: "JobIconHeadOfPersonnel"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Cryogenics
  # I mean they'll give themselves the rest of the access levels *anyways*.
  # As of 15/03/23 they can't do that so here's MOST of the rest of the access levels.
  # Head level access that isn't their own was deliberately left out, get AA from the captain instead.
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Lawyer
  - Cargo
  - Atmospherics
  - Medical
  - PlasmanAccess # Adventure
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: HoPGear
  equipment:
    shoes: ClothingShoesColorBrown
    id: HoPPDA
    gloves: ClothingHandsGlovesHop
    ears: ClothingHeadsetAltCommand
    ipc: IPCModulCommand # Adventure-IPC
    belt: BoxFolderClipboardThreePapers
    eyes: ClothingEyesHudCommand
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: HeadOfPersonnelChameleonOutfit
  job: HeadOfPersonnel
  hasMindShield: true
  equipment:
    head: ClothingHeadHatHopcap
    eyes: ClothingEyesHudCommand
    mask: ClothingMaskNeckGaiterRed
    neck: ClothingNeckCloakHop
    outerClothing: ClothingOuterWinterHoP

