- type: entity
  id: HyperExosuitFabricatorMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: гиперконвекционный фабрикатор экзокостюмов (машинная плата)
  components:
  - type: Sprite
    state: science
  - type: MachineBoard
    prototype: HyperExosuitFabricator
    stackRequirements:
      Manipulator: 7
      Glass: 5
      Plasma: 5
  - type: GuideHelp
    guides:
    - Robotics
