- type: roleLoadout
  id: JobSeniorMedicAdv
  groups:
  - GroupPlasManSuitSeniorMedic
  - GroupTankHarness
  - SeniorMedicHead
  - MedicalMask
  - SeniorMedicJumpsuit
  - MedicalGloves
  - MedicalBackpack
  - SeniorMedicOuterClothing
  - MedicalShoes
  - MedicalEyewear
  - SurvivalMedical
  - Trinkets
  - GroupSpeciesBreathToolMedical
  - BrassGroup
  - PantsGroup

- type: roleLoadout
  id: JobSeniorEngineerAdv
  groups:
  - GroupPlasManSuitSeniorEngineer
  - GroupTankHarness
  - SeniorEngineerHead
  - SeniorEngineerJumpsuit
  - SeniorEngineerBackpack
  - SeniorEngineerOuterClothing
  - SeniorEngineerShoes
  - SurvivalExtended
  - Trinkets
  - GroupSpeciesBreathTool
  - BrassGroup
  - PantsGroup

- type: roleLoadout
  id: JobSeniorResearcherAdv
  groups:
  - GroupPlasManSuitSeniorResearcher
  - GroupTankHarness
  - SeniorResearcherHead
  - SeniorResearcherNeck
  - SeniorResearcherJumpsuit
  - SeniorResearcherBackpack
  - SeniorResearcherOuterClothing
  - SeniorResearcherGloves
  - SeniorResearcherShoes
  - Glasses
  - Survival
  - Trinkets
  - GroupSpeciesBreathTool
  - BrassGroup
  - PantsGroup

- type: roleLoadout
  id: JobSeniorOfficerAdv
  groups:
  - GroupPlasManSuitSeniorOfficer
  - SeniorOfficerHead
  - SeniorOfficerNeck
  - SeniorOfficerJumpsuit
  - SeniorOfficerBackpack
  - SeniorOfficerOuterClothing
  - SeniorOfficerShoes
  - SeniorOfficerBelt
  - SurvivalSecurity
  - Trinkets
  - SecurityStar
  - GroupSpeciesBreathToolSecurity
  - BrassGroup
  - PantsGroup
