#Униформа офицера синего щита
- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitBlueshield
  name: Униформа офицера синего щита
  description: Этикетка гласит "A special suit made for the best of the elites under CentCom" Что бы это значило?
  components:
  - type: Sprite
    sprite: Adventure/Roles/blueshield/Clothing/Uniform/blueshielduniform.rsi
  - type: Clothing
    sprite: Adventure/Roles/blueshield/Clothing/Uniform/blueshielduniform.rsi

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformjumpskirtBlueshield
  name: Униформа офицера синего щита
  description: Этикетка гласит "A special suit made for the best of the elites under CentCom" Что бы это значило?
  components:
  - type: Sprite
    sprite: Adventure/Roles/blueshield/Clothing/Uniform/BSjumpskirt.rsi
  - type: Clothing
    sprite: Adventure/Roles/blueshield/Clothing/Uniform/BSjumpskirt.rsi

#Парадная униформа офицера синего щита
- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitBlueshieldParade
  name: Парадная униформа офицера синего щита
  description: Элегантная форма настоящего офицера.
  components:
  - type: Sprite
    sprite: Adventure/Roles/blueshield/Clothing/Uniform/BSformalsuit.rsi
  - type: Clothing
    sprite: Adventure/Roles/blueshield/Clothing/Uniform/BSformalsuit.rsi