#Роль
- type: job
  id: Blueshield
  name: Офицер Синий Щит
  description: Защищайте командный состав и ВИП персон Центрального Командования
  playTimeTracker: JobBlueshield
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 5h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 2h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 4h
    - !type:DepartmentTimeRequirement
      department: Command
      time: 2h
    - !type:AgeRequirement
      requiredAge: 21 # Adventure
# Adventure-edit-start
    - !type:SpeciesRequirement
      inverted: true
      species:
      - Synth
      - Zerah
      - PigMan
      - Vox
      - PlasMan
      - InsectSerpentide
# Adventure-edit-end
  startingGear: BlueshieldGear
  icon: "JobIconBlueshield"
  requireAdminNotify: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial

- type: playTimeTracker
  id: JobBlueshield

#Гир
- type: startingGear
  id: BlueshieldGear
  equipment:
    eyes: ClothingEyesGlassesBlueShield
    id: BlueshieldPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltCommand
    ipc: IPCModulSec # Adventure-IPC
  storage:
    back:
    - Flash

#Карта
- type: entity
  parent: IDCardStandard
  id: BlueshieldIDCard
  name: ID карта офицера синий щит
  components:
  - type: Sprite
    layers:
    - state: silver
    - state: stripe_top
      color: *color-centcomm-top
    - state: stripe_bottom
      color: *color-centcomm-bottom
    - sprite: &icon-rsi Interface/Misc/job_icons.rsi
      offset: &icon-offset -0.09375, 0.0625
      state: BlueShieldOfficer
  - type: Item
    heldPrefix: silver
  - type: PresetIdCard
    job: Blueshield

- type: entity
  name: кпк офицера синий щит
  parent: BasePDA
  id: BlueshieldPDA
  description: Пахнет безопасностью.
  components:
  - type: Pda
    id: BlueshieldIDCard
  - type: Appearance
    appearanceDataInit:
     enum.PdaVisuals.PdaType:
       !type:String
       pda-blueshield
  - type: PdaBorderColor
    borderColor: "#3c485a"
    accentVColor: "#3c485a"
  - type: Icon
    state: pda-blueshield

#Спавнер
- type: entity
  id: SpawnPointBlueshield
  parent: SpawnPointJobBase
  name: Офицер Синий Щит
  suffix: AdvRoles, AdvMapping
  components:
  - type: SpawnPoint
    job_id: Blueshield
  - type: Sprite
    sprite: _Adventure/Roles/blueshield/SpawnPoint.rsi
    layers:
      - state: green
      - state: Blueshield

#Иконка
- type: jobIcon
  parent: JobIcon
  id: JobIconBlueshield
  icon:
    sprite: &icon-rsi /Textures/Interface/Misc/job_icons.rsi
    state: BlueShieldOfficer
  jobName: синий щит

#Шкаф
- type: entity
  id: LockerBlueshield
  parent: LockerBase
  name: шкаф офицера синий щит
  components:
  - type: Appearance
  - type: EntityStorageVisuals
    stateBaseClosed: Blueshield
    stateDoorOpen: blueshield_open
    stateDoorClosed: Blueshield_door
  - type: AccessReader
    access: [ [ "Command" ] ]

- type: entity
  id: LockerBlueshieldFilledHardsuit
  suffix: Заполненный, Скафандр, AdvRoles, AdvMapping
  parent: LockerBlueshield
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHatBlueshieldBeret
      - id: HandheldGPSBasic
      - id: MedkitCombatFilled
      - id: MedkitFilled
      - id: HandheldCrewMonitor
      - id: ClothingOuterHardsuitBlueshield
      - id: TrackingImplanter
      - id: TrackingImplanter
      - id: TrackingImplanter
      - id: TrackingImplanter
      - id: RubberStampblueshield
      - id: WeaponX2DualphaseEnergyLaserGun
      - id: ClothingBeltSheathBS
#      - id: BSuplink Устарел и заменён на торгомат

#Печать ОСЩ by raidgo
- type: entity
  name: печать офицера синий щит
  description: Печать из резины, для проставления печатей на важных документах.
  parent: RubberStampBase
  id: RubberStampblueshield
  suffix: Adventure
  components:
  - type: Stamp
    stampedName: Синий Щит
    stampedColor: "#233D57"
    stampState: "paper_stamp-lawyer"
  - type: Sprite
    state: stamp-lawyer
