#чёрная кепка службы безопасности
- type: entity
  parent: ClothingHeadHatSecsoft
  id: ClothingHeadHatSecsoftBlack
  name: чёрная кепка службы безопасности
  description: Стильная кепка в новом, чёрном стиле.
  suffix: BORK, AdvClothing
  components:
  - type: Sprite
    sprite: Adventure/Objects/Clothing/black_security/black_secsoft.rsi
  - type: Clothing
    sprite: Adventure/Objects/Clothing/black_security/black_secsoft.rsi

- type: loadout
  id: SecurityHatBlack
  equipment:
    head: ClothingHeadHatSecsoftBlack

#чёрный берет службы безопасности
- type: entity
  parent: ClothingHeadHatBeretSecurity
  id: ClothingHeadHatBeretSecurityBlack
  name: чёрный берет службы безопасности
  description: Стильный вариант одежды для сотрудников службы безопасности.
  suffix: BORK, AdvClothing
  components:
  - type: Sprite
    sprite: Adventure/Objects/Clothing/black_security/black_beret_security.rsi
  - type: Clothing
    sprite: Adventure/Objects/Clothing/black_security/black_beret_security.rsi
  - type: Tag
    tags:
    - ClothMade

- type: loadout
  id: SecurityBeretBlack
  equipment:
    head: ClothingHeadHatBeretSecurityBlack

#чёрная фуражка смотрителя
- type: entity
  parent: ClothingHeadHatWarden
  id: ClothingHeadHatWardenBlack
  name: чёрная фуражка смотрителя
  description: Эта шляпа подчеркивает, что вы - представитель ЗАКОНА.
  suffix: BORK, AdvClothing
  components:
  - type: Sprite
    sprite: Adventure/Objects/Clothing/black_security/black_warden_hat.rsi
  - type: Clothing
    sprite: Adventure/Objects/Clothing/black_security/black_warden_hat.rsi
  - type: StealTarget
    stealGroup: ClothingHeadHatWarden

- type: loadout
  id: SecurityWardenHatBlack
  equipment:
    head: ClothingHeadHatWardenBlack

#чёрная униформа службы безопасности
- type: entity
  parent: ClothingUniformJumpsuitSec
  id: ClothingUniformJumpsuitSecBlack
  name: чёрная униформа службы безопасности
  description: Комбинезон изготовлен из прочного материала, обеспечивающего надежную защиту.
  suffix: BORK, AdvClothing
  components:
  - type: Sprite
    sprite: Adventure/Objects/Clothing/black_security/black_security_jumpsuit.rsi
  - type: Clothing
    sprite: Adventure/Objects/Clothing/black_security/black_security_jumpsuit.rsi

- type: loadout
  id: SecurityJumpsuitBlack
  equipment:
    jumpsuit: ClothingUniformJumpsuitSecBlack

#чёрная униформа смотрителя
- type: entity
  parent: ClothingUniformJumpsuitWarden
  id: ClothingUniformJumpsuitWardenBlack
  name: чёрная униформа смотрителя
  description: Официальный защитный костюм для офицеров.
  suffix: BORK, AdvClothing
  components:
  - type: Sprite
    sprite: Adventure/Objects/Clothing/black_security/black_warden_jumpsuit.rsi
  - type: Clothing
    sprite: Adventure/Objects/Clothing/black_security/black_warden_jumpsuit.rsi

- type: loadout
  id: SecurityWardenJumpsuitBlack
  equipment:
    jumpsuit: ClothingUniformJumpsuitWardenBlack

#чёрная бронекуртка смотрителя
- type: entity
  parent: ClothingOuterCoatWarden
  id: ClothingOuterCoatWardenBlack
  name: чёрная бронекуртка смотрителя
  description: Прочная, практичная куртка, предназначенная для защиты смотрителя от любых угроз.
  suffix: BORK, AdvClothing
  components:
  - type: Sprite
    sprite: Adventure/Objects/Clothing/black_security/black_warden_coats.rsi
  - type: Clothing
    sprite: Adventure/Objects/Clothing/black_security/black_warden_coats.rsi

- type: loadout
  id: SecurityWardenCoatBlack
  equipment:
    outerClothing: ClothingOuterCoatWardenBlack

#мантия смотрителя
- type: entity
  parent: ClothingNeckBase
  id: ClothingNeckMantleWarden
  name: мантия смотрителя
  description: Простая мантия почётных офицеров службы безопасности.
  suffix: BORK, AdvClothing
  components:
  - type: Sprite
    sprite: Adventure/Objects/Clothing/black_security/warden_mantle.rsi
  - type: Clothing
    sprite: Adventure/Objects/Clothing/black_security/warden_mantle.rsi

- type: loadout
  id: NeckWarden
  equipment:
    neck: ClothingNeckMantleWarden
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterWarden

- type: loadoutEffectGroup
  id: MasterWarden
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobWarden
      time: 36000 #10 hrs

#накидка службы безопасности
- type: entity
  parent: ClothingNeckBase
  id: ClothingNeckMantleSecurity
  name: накидка службы безопасности
  description: почётная накидка ветерана службы безопасности.
  suffix: BORK, AdvClothing
  components:
  - type: Sprite
    sprite: Adventure/Objects/Clothing/black_security/security_mantle.rsi
  - type: Clothing
    sprite: Adventure/Objects/Clothing/black_security/security_mantle.rsi

- type: loadout
  id: NeckSecurityOfficer
  equipment:
    neck: ClothingNeckMantleSecurity
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterSecurityOfficer

- type: loadoutEffectGroup
  id: MasterSecurityOfficer
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 72000 #20 hrs