#Комбинезон ЦСС
- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitCLEA
  name: комбинезон ЦСС
  description: Теперь в новой цветовой гамме!
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_uniform.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_uniform.rsi

#Шлем ЦСС
- type: entity
  parent: ClothingHeadBase
  id: ClothingHeadHelmetCLEA
  name: шлем ЦСС
  description: Им можно колоть орехи.
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_Helmet.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_Helmet.rsi
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.90
        Slash: 0.90
        Piercing: 0.90
        Heat: 0.90
  - type: FlashImmunity
  - type: EyeProtection
    protectionTime: 5

#Кепка офицера ЦСС
- type: entity
  parent: ClothingHeadBase
  id: ClothingHeadBaseCapCLEA
  name: кепка офицера ЦСС
  description: Повседневный головной убор ЦСС.
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_cap.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_cap.rsi

#Гарнитура-наушники ЦСС
- type: entity
  name: гарнитура-наушники ЦСС
  parent: ClothingHeadsetAltCentCom
  id: CLEAHeadsetAlt
  description: Гарнитура, оснащенная подавляющими наушниками.
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_Headset.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_Headset.rsi

#Защитные очки ЦСС
- type: entity
  parent: [ClothingEyesGlassesSunglasses, ShowSecurityIcons]
  id: ClothingEyesGlassesCLEA
  description: Очки, защищающие глаза от яркого света.
  name: защитные очки ЦСС
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_glasses.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_glasses.rsi
  - type: FlashImmunity
  - type: EyeProtection
    protectionTime: 5

#Боевые перчатки ЦСС
- type: entity
  parent: ClothingHandsGlovesColorBlack
  id: ClothingHandsGlovesCLEA
  name: боевые перчатки ЦСС
  description: Тактический перчатки элитных солдат.
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_Gloves.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_Gloves.rsi
  - type: Insulated
  - type: Fiber
    fiberMaterial: fibers-insulative

#Противогаз ЦСС
- type: entity
  parent: ClothingMaskGas
  id: ClothingMaskCLEA
  name: противогаз ЦСС
  description: Не освежает дыхание.
  components:
  - type: Item
    size: Tiny
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_mask.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_mask.rsi
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.95
        Slash: 0.95
        Piercing: 0.95
        Heat: 0.95
  - type: IngestionBlocker
  - type: IdentityBlocker
  - type: Tag
    tags:
    - HidesHair
  - type: FlashImmunity
  - type: EyeProtection
    protectionTime: 5

#РПС ЦСС
- type: entity
  parent: [ClothingBeltSecurityWebbing, ContentsExplosionResistanceBase]
  id: ClothingBeltMilitaryWebbingCLEA
  name: РПС ЦСС
  description: Не сковывает движений!
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_Webbing.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_Webbing.rsi
  - type: ExplosionResistance
    damageCoefficient: 0.5

#Боевой Бронежилет ЦСС
- type: entity
  parent: ClothingOuterBaseMedium
  id: ClothingOuterArmorCLEA
  name: боевой бронежилет ЦСС
  description: Стандартный армейский бронежилет.
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_armor.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_armor.rsi
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.80
        Slash: 0.80
        Piercing: 0.80
        Heat: 0.80
  - type: ExplosionResistance
    damageCoefficient: 0.90
  - type: AllowSuitStorage

#Рюкзак ЦСС
- type: entity
  parent: ClothingBackpackERTSecurity
  id: ClothingMilitaryBackpackCLEA
  name: рюкзак ЦСС
  description: Это очень робастный рюкзак.
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_BackPack.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_BackPack.rsi
  - type: StorageFill
    contents:
    - id: BoxZiptie
    - id: CrowbarRed
    - id: DoubleEmergencyOxygenTankFilled

#ID карта ЦСС
- type: entity
  parent: IDCardStandard
  id: CLEAIDCard
  name: ID карта Солдата ЦСС
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/CLEA/other/CLEA_IDcard.rsi
    layers:
    - state: silver
    - state: idCLEA
  - type: PresetIdCard
    job: CLEASoldier
  - type: Item
    heldPrefix: silver

#ID карта офицера ЦСС
- type: entity
  parent: IDCardStandard
  id: CLEAOfficerIDCard
  name: ID карта Офицера ЦСС
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/CLEA/other/CLEA_IDcard.rsi
    layers:
    - state: silver
    - state: idCLEA
  - type: PresetIdCard
    job: CLEAOfficer
  - type: Item
    heldPrefix: silver

#КПК солдата ЦСС
- type: entity
  parent: BasePDA
  id: CLEAPDA
  name: КПК Солдата ЦСС
  description: Не такой робастный, как у отряда быстрого реагирования.
  components:
  - type: Pda
    id: CLEAIDCard
  - type: Appearance
    appearanceDataInit:
     enum.PdaVisuals.PdaType:
       !type:String
       pda-CLEA
  - type: PdaBorderColor
    borderColor: "#4e4e56"
  - type: Icon
    state: pda-CLEA

#КПК офицера ЦСС
- type: entity
  parent: BasePDA
  id: CLEAOfficerPDA
  name: КПК Офицера ЦСС
  description: Не такой робастный, как у отряда быстрого реагирования.
  components:
  - type: Pda
    id: CLEAOfficerIDCard
  - type: Appearance
    appearanceDataInit:
     enum.PdaVisuals.PdaType:
       !type:String
       pda-CLEAOfficer
  - type: PdaBorderColor
    borderColor: "#4e4e56"
  - type: Icon
    state: pda-CLEAOfficer

#Скафандр ЦСС
- type: entity
  parent: ClothingOuterHardsuitSecurity
  id: ClothingOuterHardsuitCLEA
  name: скафандр солдата ЦСС
  description: Базовый боевой скафандр центральных силовых структур.
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_hardhuit/CLEA_hardhuit.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_hardhuit/CLEA_hardhuit.rsi
  - type: PressureProtection
    highPressureMultiplier: 0.5
    lowPressureMultiplier: 1000
  - type: ExplosionResistance
    damageCoefficient: 0.7
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.65
        Slash: 0.65
        Piercing: 0.65
        Caustic: 0.65
  - type: ClothingSpeedModifier
    walkModifier: 0.85
    sprintModifier: 0.85
  - type: HeldSpeedModifier
  - type: ToggleableClothing
    clothingPrototype: ClothingHeadHelmetHardsuitCLEA

- type: entity
  parent: ClothingHeadHardsuitBase
  id: ClothingHeadHelmetHardsuitCLEA
  name: шлем скафандра солдата ЦСС
  description: Таким шлемом можно колоть орехи.
  components:
  - type: BreathMask
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_hardhuit/CLEA_hardhuit_helmet.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_hardhuit/CLEA_hardhuit_helmet.rsi
  - type: PressureProtection
    highPressureMultiplier: 0.3
    lowPressureMultiplier: 1000

#Скафандр офицера ЦСС
- type: entity
  parent: ClothingOuterHardsuitSecurity
  id: ClothingOuterHardsuitCLEAOfficer
  name: скафандр офицера ЦСС
  description: Базовый боевой скафандр центральных силовых структур.
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_hardhuit/CLEA_hardhuit_Officer.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_hardhuit/CLEA_hardhuit_Officer.rsi
  - type: PressureProtection
    highPressureMultiplier: 0.5
    lowPressureMultiplier: 1000
  - type: ExplosionResistance
    damageCoefficient: 0.6
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.60
        Slash: 0.60
        Piercing: 0.60
        Caustic: 0.60
  - type: ClothingSpeedModifier
    walkModifier: 0.90
    sprintModifier: 0.90
  - type: HeldSpeedModifier
  - type: ToggleableClothing
    clothingPrototype: ClothingHeadHelmetHardsuitCLEAOfficer

- type: entity
  parent: ClothingHeadHardsuitBase
  id: ClothingHeadHelmetHardsuitCLEAOfficer
  name: шлем скафандра офицера ЦСС
  description: Таким шлемом можно колоть орехи.
  components:
  - type: BreathMask
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_hardhuit/CLEA_hardhuit_helmet_Officer.rsi
  - type: Clothing
    sprite: _Adventure/Roles/SpecialForces/CLEA/CLEA_hardhuit/CLEA_hardhuit_helmet_Officer.rsi
  - type: PressureProtection
    highPressureMultiplier: 0.3
    lowPressureMultiplier: 1000
