#Иконка ЦСС
- type: jobIcon
  parent: JobIcon
  id: JobIconCLEA
  icon:
    sprite: /Textures/_Adventure/Roles/SpecialForces/CLEA/other/CLEA_icon.rsi
    state: CLEA
  jobName: ЦСС

#ГИР солдата ЦСС Base
- type: startingGear
  id: CLEAGearBase
  equipment:
    jumpsuit: ClothingUniformJumpsuitCLEA
    back: ClothingMilitaryBackpackCLEA
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHelmetCLEA
    gloves: ClothingHandsGlovesCLEA
    outerClothing: ClothingOuterArmorCLEA
    mask: ClothingMaskCLEA
    id: CLEAPDA
    belt: ClothingBeltMilitaryWebbingCLEA
    ears: CLEAHeadsetAlt
    eyes: ClothingEyesGlassesCLEA
    pocket1: CLEAuplink
    ipc: IPCModulSec

#ГИР Офицера ЦСС Base
- type: startingGear
  id: CLEAGearOfficerBase
  equipment:
    jumpsuit: ClothingUniformJumpsuitCLEA
    back: ClothingMilitaryBackpackCLEA
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadBaseCapCLEA
    gloves: ClothingHandsGlovesCLEA
    outerClothing: ClothingOuterArmorCLEA
    mask: ClothingMaskCLEA
    id: CLEAOfficerPDA
    belt: ClothingBeltMilitaryWebbingCLEA
    ears: CLEAHeadsetAlt
    eyes: ClothingEyesGlassesCLEA
    pocket1: CLEAuplinkleader
    ipc: IPCModulSec

# госторолька солдат
- type: randomHumanoidSettings
  id: CLEABase
  randomizeName: false
  components:
  - type: MindShield
  - type: GhostRole
    name: Солдат ЦСС
    description: Солдат отряда Центральных Силовых Структур. Пора решать проблемы.
    job: CLEASoldier
  - type: GhostTakeoverAvailable
  - type: Loadout
    prototypes: [ CLEAGearBase ]
  - type: RandomMetadata
    nameSegments:
    - FirstNamesSoldiers
    - LastNamesSoldiers
    nameFormat: name-format-soldiers
  - type: AntagImmune
  # NOTE(c4llv07e): uncomment this on TTS merge
  # - type: TTS
  #   voice: officer_enclave

- type: entity
  id: RandomHumanoidSpawnerCLEABase
  name: Солдат ЦСС
  suffix: BASE
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/CLEA/other/CLEA_roles.rsi
    state: Solder
  - type: RandomMetadata
    nameSegments:
    - FirstNamesSoldiers
    - LastNamesSoldiers
    nameFormat: name-format-soldiers
  - type: RandomHumanoidSpawner
    settings: CLEABase
  - type: AntagImmune
# /госторолька солдат

# госторолька офицер
- type: randomHumanoidSettings
  id: CLEAOfficer
  randomizeName: false
  components:
  - type: MindShield
  - type: GhostRole
    name: Офицер ЦСС
    description: Офицер отряда Центральных Силовых Структур. Пора решать проблемы. #придумаешь сам
    job: CLEAOfficer
  - type: GhostTakeoverAvailable
  - type: Loadout
    prototypes: [ CLEAGearOfficerBase ]
  - type: RandomMetadata
    nameSegments:
    - FirstNamesOfficers
    - LastNamesOfficers
    nameFormat: name-format-officers
  - type: AntagImmune
  # NOTE(c4llv07e): uncomment this on TTS merge
  # - type: TTS
  #   voice: officer_enclave

- type: entity
  id: RandomHumanoidSpawnerCLEAOfficer
  name: Офицер ЦСС
  suffix: BASE
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/CLEA/other/CLEA_roles.rsi
    state: Officer
  - type: RandomMetadata
    nameSegments:
    - FirstNamesOfficers
    - LastNamesOfficers
    nameFormat: name-format-officers
  - type: RandomHumanoidSpawner
    settings: CLEAOfficer
  - type: AntagImmune
# /госторолька офицер

# Стартовый гир FullEVA
- type: startingGear
  id: CLEAGearFullEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitCLEA
    back: ClothingMilitaryBackpackCLEA
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesCLEA
    outerClothing: ClothingOuterHardsuitCLEA
    mask: ClothingMaskCLEA
    id: CLEAPDA
    belt: ClothingBeltMilitaryWebbingCLEA
    ears: CLEAHeadsetAlt
    eyes: ClothingEyesGlassesCLEA
    pocket1: CLEAuplink
    ipc: IPCModulSec

# Стартовый гир офицера FullEVA
- type: startingGear
  id: CLEAGearOfficerFullEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitCLEA
    back: ClothingMilitaryBackpackCLEA
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesCLEA
    outerClothing: ClothingOuterHardsuitCLEAOfficer
    mask: ClothingMaskCLEA
    id: CLEAOfficerPDA
    belt: ClothingBeltMilitaryWebbingCLEA
    ears: CLEAHeadsetAlt
    eyes: ClothingEyesGlassesCLEA
    pocket1: CLEAuplinkleader
    ipc: IPCModulSec

- type: randomHumanoidSettings
  id: CLEAOfficerEVA
  randomizeName: false
  components:
  - type: MindShield
  - type: GhostRole
    name: Офицер ЦСС
    description: Офицер отряда Центральных Силовых Структур. Пора решать проблемы. #придумаешь сам
  - type: GhostTakeoverAvailable
  - type: Loadout
    prototypes: [ CLEAGearOfficerFullEVA ]
  - type: RandomMetadata
    nameSegments:
    - FirstNamesOfficers
    - LastNamesOfficers
    nameFormat: name-format-officers
  - type: AntagImmune

- type: entity
  id: RandomHumanoidSpawnerCLEAOfficerEVA
  name: Офицер ЦСС
  suffix: EVA
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/CLEA/other/CLEA_roles.rsi
    state: Officer
  - type: RandomMetadata
    nameSegments:
    - FirstNamesOfficers
    - LastNamesOfficers
    nameFormat: name-format-officers
  - type: RandomHumanoidSpawner
    settings: CLEAOfficerEVA
  - type: AntagImmune

- type: randomHumanoidSettings
  id: CLEABaseEVA
  randomizeName: false
  components:
  - type: MindShield
  - type: GhostRole
    name: Солдат ЦСС
    description: Солдат отряда Центральных Силовых Структур. Пора решать проблемы. #придумаешь сам
  - type: GhostTakeoverAvailable
  - type: Loadout
    prototypes: [ CLEAGearFullEVA ]
  - type: RandomMetadata
    nameSegments:
    - FirstNamesSoldiers
    - LastNamesSoldiers
    nameFormat: name-format-soldiers
  - type: AntagImmune

- type: entity
  id: RandomHumanoidSpawnerCLEABaseEVA
  name: Солдат ЦСС
  suffix: EVA
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/CLEA/other/CLEA_roles.rsi
    state: Solder
  - type: RandomMetadata
    nameSegments:
    - FirstNamesSoldiers
    - LastNamesSoldiers
    nameFormat: name-format-soldiers
  - type: RandomHumanoidSpawner
    settings: CLEABaseEVA
  - type: AntagImmune

# Джобки

- type: playTimeTracker
  id: JobCLEAOfficer

- type: playTimeTracker
  id: JobCLEASoldier

- type: job
  id: CLEAOfficer
  name: Офицер ЦСС
  description: Офицер отряда Центральных Силовых Структур. Пора решать проблемы.
  playTimeTracker: JobCLEAOfficer
  setPreference: false
  startingGear: CLEAGearOfficerBase
  icon: "JobIconCLEA"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: job
  id: CLEASoldier
  name: Солдат ЦСС
  description: Солдат отряда Центральных Силовых Структур. Пора решать проблемы.
  playTimeTracker: JobCLEASoldier
  setPreference: false
  startingGear: CLEAGearBase
  icon: "JobIconCLEA"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
