#Роль
- type: job
  id: Blueshield
  name: офицер синий щит
  description: Защищайте командный состав и ВИП персон Центрального Командования
  playTimeTracker: JobBlueshield
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 18000 #5 hrs # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 3600 #1 hrs # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10800 #3 hrs # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Command
      time: 3600 # 1 hours
    - !type:AgeRequirement
      requiredAge: 30 # Adventure
  startingGear: BlueshieldGear
  icon: "JobIconBlueshield"
  requireAdminNotify: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial

- type: playTimeTracker
  id: JobBlueshield

#Гир
- type: startingGear
  id: BlueshieldGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: BlueshieldPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - Flash

#Карта
- type: entity
  parent: IDCardStandard
  id: BlueshieldIDCard
  name: ID карта офицера синего щита
  components:
  - type: Sprite
    sprite: Adventure/Roles/blueshield/PDA/ID.rsi
    layers:
    - state: silver
    - state: idblueshield
  - type: Item
    heldPrefix: silver
  - type: PresetIdCard
    job: Blueshield

- type: entity
  name: Кпк офицера синего щита
  parent: BasePDA
  id: BlueshieldPDA
  description: Пахнет безопасностью
  components:
  - type: Sprite
    sprite: Adventure/Roles/blueshield/PDA/PDA.rsi
    layers:
    - map: [ "enum.PdaVisualLayers.Base" ]
    - state: "light_overlay"
      map: [ "enum.PdaVisualLayers.Flashlight" ]
      shader: "unshaded"
      visible: false
    - state: "id_overlay"
      map: [ "enum.PdaVisualLayers.IdLight" ]
      shader: "unshaded"
      visible: false
  - type: Pda
    id: BlueshieldIDCard
    state: pda-blueshield
  - type: PdaBorderColor
    borderColor: "#3c485a"
    accentVColor: "#3c485a"
  - type: Icon
    sprite: Adventure/Roles/blueshield/PDA/PDA.rsi
    state: pda-blueshield

#Спавнер
- type: entity
  id: SpawnPointBlueshield
  parent: SpawnPointJobBase
  name: Офицер Синий Щит
  suffix: AdvRoles, AdvMapping
  components:
  - type: SpawnPoint
    job_id: Blueshield
  - type: Sprite
    sprite: Adventure/Roles/blueshield/SpawnPoint.rsi
    layers:
      - state: green
      - state: Blueshield

#Иконка
- type: jobIcon
  parent: JobIcon
  id: JobIconBlueshield
  icon:
    sprite: /Textures/Adventure/Roles/blueshield/PDA/JobIcons.rsi
    state: BlueShieldOfficer
  jobName: синий щит

#Шкаф
- type: entity
  id: LockerBlueshield
  parent: LockerBase
  name: Шкаф Офицера синего щита
  suffix: AdvRoles, AdvMapping
  components:
  - type: Appearance
  - type: EntityStorageVisuals
    stateBaseClosed: Blueshield
    stateDoorOpen: blueshield_open
    stateDoorClosed: Blueshield_door
  - type: AccessReader
    access: [ [ "Command" ] ]

- type: entity
  id: LockerBlueshieldFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerBlueshield
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHatBlueshieldBeret
      - id: HandheldGPSBasic
      - id: MedkitCombatFilled
      - id: MedkitFilled
      - id: HandheldCrewMonitor
      - id: ClothingOuterHardsuitBlueshield
      - id: TrackingImplanter
      - id: TrackingImplanter
      - id: RubberStampblueshield

#Печать ОСЩ by raidgo
- type: entity
  name: печать офицера синего щита
  parent: RubberStampBase
  id: RubberStampblueshield
  suffix: Adventure
  components:
  - type: Stamp
    stampedName: Синий Щит
    stampedColor: "#233D57"
    stampState: "paper_stamp-lawyer"
  - type: Sprite
    state: stamp-lawyer
