- type: department
  id: Cargo
  name: department-Cargo
  description: department-Cargo-description
  color: "#efb873" # Adventure
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist

- type: department
  id: Civilian
  name: department-Civilian
  description: department-Civilian-description
  color: "#72cf09" # Adventure
  weight: -10
  roles:
  - Bartender
  - Botanist
  - Boxer
  - Chaplain
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  - Lawyer
  - Librarian
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - Zookeeper
  - ServiceWorker

- type: department
  id: CentralCommand
  name: department-CentralCommand
  description: department-CentralCommand-description
  color: "#2c9ecb" # Adventure
  roles:
  - CentralCommandOfficial
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  - CLEASoldier # Adventure
  - CLEAOfficer # Adventure
  editorHidden: true
  weight: 120

- type: department
  id: Command
  name: department-Command
  description: department-Command-description
  color: "#2681a5" # Adventure
  roles:
  - Captain
  - IAA # Corvax-IAA
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
  - Blueshield #Adventure
  # Adv jobban- CentralCommandOfficial
  # Adv jobban- CBURN
  # Adv jobban- ERTLeader
  # Adv jobban- ERTChaplain
  # Adv jobban- ERTJanitor
  # Adv jobban- ERTMedical
  # Adv jobban- ERTSecurity
  # Adv jobban- ERTEngineer
  # Adv jobban- DeathSquad
  primary: false
  weight: 100

- type: department
  id: Engineering
  name: department-Engineering
  description: department-Engineering-description
  color: "#EFB341"
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - SeniorEngineerAdv # Adventure
  - StationEngineer
  - TechnicalAssistant

- type: department
  id: Medical
  name: department-Medical
  description: department-Medical-description
  color: "#90d6ff" # Adventure
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - SeniorMedicAdv # Adventure
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic

- type: department
  id: Security
  name: department-Security
  description: department-Security-description
  color: "#fd7f7f" # Adventure
  weight: 20
  roles:
  - HeadOfSecurity
  - SeniorOfficerAdv # Adventure
  - SecurityCadet
  - SecurityOfficer
  - Pilot # Corvax-Pilot
  - Detective
  - Warden
  - Brigmedic #Adventure

- type: department
  id: Science
  name: department-Science
  description: department-Science-description
  color: "#f79df7" # Adventure
  roles:
  - ResearchDirector
  - SeniorResearcherAdv # Adventure
  - Scientist
  - ResearchAssistant

- type: department
  id: Silicon
  name: department-Silicon
  description: department-Silicon-description
  color: "#D381C9"
  roles:
  - Borg
  - StationAi
