using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Adventure.Roles.CCO.Console;

[GenerateTypedNameReferences]
public sealed partial class CcoConsoleSquadControl : Control
{
    public CcoConsoleSquadControl(CcoConsoleBoundInterface bui,
        string prototypeID,
        string name,
        string description,
        bool canCall)
    {
        RobustXamlLoader.Load(this);

        Name.Text = name;
        Description.SetMessage(description);

        StartRitualButton.OnPressed += _ => bui.SendSpecialSquad(prototypeID);
        StartRitualButton.Disabled = canCall;
    }
}
