#Иконка ЦСС
- type: jobIcon
  parent: JobIcon
  id: JobIconCLEA
  icon:
    sprite: /Textures/Adventure/Roles/CLEA/other/CLEA_icon.rsi
    state: CLEA
  jobName: ЦСС

#ГИР солдата ЦСС Base
- type: startingGear
  id: CLEAGearBase
  equipment:
    jumpsuit: ClothingUniformJumpsuitCLEA
    back: ClothingMilitaryBackpackCLEA
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHelmetCLEA
    gloves: ClothingHandsGlovesCLEA
    outerClothing: ClothingOuterArmorCLEA
    mask: ClothingMaskCLEA
    id: CLEAPDA
    belt: ClothingBeltMilitaryWebbingCLEA
    pocket1: WeaponPistolMk58
    suitstorage: WeaponRifleLecter
    ears: CLEAHeadsetAlt
    eyes: ClothingEyesGlassesCLEA

#ГИР Офицера ЦСС Base
- type: startingGear
  id: CLEAGearOfficerBase
  equipment:
    jumpsuit: ClothingUniformJumpsuitCLEA
    back: ClothingMilitaryBackpackCLEA
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadBaseCapCLEA
    gloves: ClothingHandsGlovesCLEA
    outerClothing: ClothingOuterArmorCLEA
    mask: ClothingMaskCLEA
    id: CLEAOfficerPDA
    belt: ClothingBeltMilitaryWebbingCLEA
    pocket1: WeaponPistolMk58
    suitstorage: WeaponRifleLecter
    ears: CLEAHeadsetAlt
    eyes: ClothingEyesGlassesCLEA

# госторолька солдат
- type: randomHumanoidSettings
  id: CLEABase
  randomizeName: false
  components:
    - type: MindShield
    - type: GhostRole
      name: Солдат ЦСС
      description: Солдат отряда Центральных Силовых Структур. Пора решать проблемы.
    - type: GhostTakeoverAvailable
    - type: Loadout
      prototypes: [ CLEAGearBase ]
    - type: RandomMetadata
      nameSegments:
      - NamesFirstCLEABase
      - NamesLastCLEABase
    - type: AntagImmune
    - type: TTS
      voice: officer_enclave

- type: entity
  id: RandomHumanoidSpawnerCLEABase
  name: Солдат ЦСС
  suffix: BASE
  components:
    - type: Sprite
      sprite: Adventure/Roles/CLEA/other/CLEA_roles.rsi
      state: Solder
    - type: RandomMetadata
      nameSegments:
      - NamesFirstCLEABase
      - NamesLastCLEABase
    - type: RandomHumanoidSpawner
      settings: CLEABase
    - type: AntagImmune

- type: dataset
  id: NamesFirstCLEABase
  values:
  - Рядовой
  - Ефрейтор

- type: dataset
  id: NamesLastCLEABase
  values:
  - Ястреб
  - Ворон
  - Бугор
  - Браво
  - Фокс
  - Хикс
  - Гроза
  - Каир
  - Геварра
  - Рекс
  - Вольф
  - Бизон
# /госторолька солдат

# госторолька офицер
- type: randomHumanoidSettings
  id: CLEAOfficer
  randomizeName: false
  components:
    - type: MindShield
    - type: GhostRole
      name: Офицер ЦСС
      description: Офицер отряда Центральных Силовых Структур. Пора решать проблемы. #придумаешь сам
    - type: GhostTakeoverAvailable
    - type: Loadout
      prototypes: [ CLEAGearOfficerBase ]
    - type: RandomMetadata
      nameSegments:
      - NamesFirstCLEAOfficer
      - NamesLastCLEAOfficer
    - type: AntagImmune
    - type: TTS
      voice: officer_enclave

- type: entity
  id: RandomHumanoidSpawnerCLEAOfficer
  name: Офицер ЦСС
  suffix: BASE
  components:
    - type: Sprite
      sprite: Adventure/Roles/CLEA/other/CLEA_roles.rsi
      state: Officer
    - type: RandomMetadata
      nameSegments:
      - NamesFirstCLEAOfficer
      - NamesLastCLEAOfficer
    - type: RandomHumanoidSpawner
      settings: CLEAOfficer
    - type: AntagImmune

- type: dataset
  id: NamesFirstCLEAOfficer
  values:
  - Лейтенант
  - Капитан
  - Майор

- type: dataset
  id: NamesLastCLEAOfficer
  values:
  - Ястреб
  - Ворон
  - Бугор
  - Браво
  - Фокс
  - Хикс
  - Гроза
  - Каир
  - Геварра
  - Рекс
  - Вольф
  - Бизон
# /госторолька офицер

# Стартовый гир FullEVA
- type: startingGear
  id: CLEAGearFullEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitCLEA
    back: ClothingMilitaryBackpackCLEA
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesCLEA
    outerClothing: ClothingOuterHardsuitCLEA
    mask: ClothingMaskCLEA
    id: CLEAPDA
    belt: ClothingBeltMilitaryWebbingCLEA
    pocket1: WeaponPistolMk58
    suitstorage: WeaponRifleLecter
    ears: CLEAHeadsetAlt
    eyes: ClothingEyesGlassesCLEA

# Стартовый гир офицера FullEVA
- type: startingGear
  id: CLEAGearOfficerFullEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitCLEA
    back: ClothingMilitaryBackpackCLEA
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesCLEA
    outerClothing: ClothingOuterHardsuitCLEAOfficer
    mask: ClothingMaskCLEA
    id: CLEAOfficerPDA
    belt: ClothingBeltMilitaryWebbingCLEA
    pocket1: WeaponPistolMk58
    suitstorage: WeaponRifleLecter
    ears: CLEAHeadsetAlt
    eyes: ClothingEyesGlassesCLEA

- type: randomHumanoidSettings
  id: CLEAOfficerEVA
  randomizeName: false
  components:
    - type: MindShield
    - type: GhostRole
      name: Офицер ЦСС
      description: Офицер отряда Центральных Силовых Структур. Пора решать проблемы. #придумаешь сам
    - type: GhostTakeoverAvailable
    - type: Loadout
      prototypes: [ CLEAGearOfficerFullEVA ]
    - type: RandomMetadata
      nameSegments:
      - NamesFirstCLEAOfficer
      - NamesLastCLEAOfficer
    - type: AntagImmune

- type: entity
  id: RandomHumanoidSpawnerCLEAOfficerEVA
  name: Офицер ЦСС
  suffix: EVA
  components:
    - type: Sprite
      sprite: Adventure/Roles/CLEA/other/CLEA_roles.rsi
      state: Officer
    - type: RandomMetadata
      nameSegments:
      - NamesFirstCLEAOfficer
      - NamesLastCLEAOfficer
    - type: RandomHumanoidSpawner
      settings: CLEAOfficerEVA
    - type: AntagImmune

- type: randomHumanoidSettings
  id: CLEABaseEVA
  randomizeName: false
  components:
    - type: MindShield
    - type: GhostRole
      name: Солдат ЦСС
      description: Солдат отряда Центральных Силовых Структур. Пора решать проблемы. #придумаешь сам
    - type: GhostTakeoverAvailable
    - type: Loadout
      prototypes: [ CLEAGearFullEVA ]
    - type: RandomMetadata
      nameSegments:
      - NamesFirstCLEABase
      - NamesLastCLEABase
    - type: AntagImmune

- type: entity
  id: RandomHumanoidSpawnerCLEABaseEVA
  name: Солдат ЦСС
  suffix: EVA
  components:
    - type: Sprite
      sprite: Adventure/Roles/CLEA/other/CLEA_roles.rsi
      state: Solder
    - type: RandomMetadata
      nameSegments:
      - NamesFirstCLEABase
      - NamesLastCLEABase
    - type: RandomHumanoidSpawner
      settings: CLEABaseEVA
    - type: AntagImmune
