#магматитовый скафандр
- type: entity
  parent: ClothingOuterHardsuitGoliath
  id: ClothingOuterHardsuitMagma
  suffix: LavaLand
  name: магматитовый скафандр утилизатора
  description: Скафандр утилизатора, укреплённый магматитовой рудой.
  components:
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/Equipment/MagmaSuit/suit.rsi
    layers:
    - state: icon
    - state: icon-lava
      shader: unshaded
  - type: Clothing
    sprite: Adventure/Roles/LavaLand/Equipment/MagmaSuit/suit.rsi  
    clothingVisuals:
      outerClothing:
      - state: equipped-OUTERCLOTHING
      - state: equipped-OUTERCLOTHING-lava
        shader: unshaded
      outerClothing-reptilian:
      - state: equipped-OUTERCLOTHING-reptilian
      - state: equipped-OUTERCLOTHING-reptilian-lava
        shader: unshaded
  - type: PressureProtection
    highPressureMultiplier: 0.5
    lowPressureMultiplier: 1000
  - type: ExplosionResistance
    damageCoefficient: 0.2
  - type: TemperatureProtection
    heatingCoefficient: 0.001
    coolingCoefficient: 0.001
  - type: FireProtection
    reduction: 0.8
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.5
        Slash: 0.5
        Piercing: 0.5
        Heat: 0.2
        Radiation: 0.3
        Caustic: 0.8
  - type: ClothingSpeedModifier
    walkModifier: 0.8
    sprintModifier: 0.8
  - type: HeldSpeedModifier
  - type: ToggleableClothing
    clothingPrototype: ClothingHeadHelmetHardsuitMagma
  - type: Construction
    graph: HardsuitMagma
    node: hardsuitmagma
  - type: PointLight
    radius: 2
    energy: 1.5
    color: "#f2511e"

- type: entity
  parent: ClothingHeadHelmetHardsuitSalvage
  id: ClothingHeadHelmetHardsuitMagma
  name: шлем магматитовый скафандр утилизатора
  description: Шлем утилизатора в магматитовой обёртке.
  components:
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/Equipment/MagmaSuit/helmet.rsi
    layers:
    - state: icon
    - state: icon-lava
      shader: unshaded
    - state: icon-flash
    - state: icon-lava
      visible: false
      shader: unshaded
      map: [ "light" ]
  - type: ToggleableLightVisuals
    spriteLayer: light
    clothingVisuals:
      head:
      - state: on-equipped-HELMET
      - state: equipped-HELMET-lava
        shader: unshaded
      head-reptilian:
      - state: on-equipped-HELMET-reptilian
      - state: equipped-HELMET-lava
        shader: unshaded
  - type: Clothing
    sprite: Adventure/Roles/LavaLand/Equipment/MagmaSuit/helmet.rsi
    clothingVisuals:
      head:
      - state: off-equipped-HELMET
      - state: equipped-HELMET-lava
        shader: unshaded
      head-reptilian:
      - state: off-equipped-HELMET-reptilian
      - state: equipped-HELMET-lava
        shader: unshaded
  - type: TemperatureProtection
    heatingCoefficient: 0.005
    coolingCoefficient: 0.005
  - type: FireProtection
    reduction: 0.2
  - type: PressureProtection
    highPressureMultiplier: 0.525
    lowPressureMultiplier: 1000
  - type: PointLight
    color: "#fda144" 
    radius: 7
    energy: 5

# крафт
- type: constructionGraph
  id: HardsuitMagma
  start: start
  graph:
  - node: start
    edges:
    - to: hardsuitmagma
      steps:
      - tag: HardsuitSpatio
        icon:
          sprite: Clothing/OuterClothing/Hardsuits/spatio.rsi
          state: icon
        name: spationaut hardsuit
        doAfter: 10
      - material: Durathread
        amount: 10
        doAfter: 10
      - material: Magmatite
        amount: 5
        doAfter: 10
  - node: hardsuitmagma
    entity: ClothingOuterHardsuitMagma

- type: construction
  name: магматитовый скафандр утилизатора
  id: HardsuitMagma
  graph: HardsuitMagma
  startNode: start
  targetNode: hardsuitmagma
  category: construction-category-clothing
  objectType: Item
  description: Скафандр утилизатора, укреплённый магматитовой рудой.
  icon:
    sprite: Adventure/Roles/LavaLand/Equipment/MagmaSuit/suit.rsi
    state: icon

#магматитовый скафандр шахтёра
- type: Tag
  id: HardsuitSalvage

- type: entity
  parent: ClothingOuterHardsuitMagma
  id: ClothingOuterHardsuitMagmaSalvage
  suffix: LavaLand
  name: магматитовый скафандр шахтёра
  description: Скафандр шахтёра, укреплённый магматитовой рудой.
  components:
  - type: ToggleableClothing
    clothingPrototype: ClothingHeadHelmetHardsuitMagmaSalvage
  - type: ClothingSpeedModifier
    walkModifier: 0.75
    sprintModifier: 0.75
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.45
        Slash: 0.45
        Piercing: 0.45
        Heat: 0.15
        Radiation: 0.3
        Caustic: 0.8
  - type: Construction
    graph: HardsuitMagmaSalvage
    node: hardsuitmagmasalvage

- type: entity
  parent: ClothingHeadHelmetHardsuitMagma
  id: ClothingHeadHelmetHardsuitMagmaSalvage
  name: шлем магматитовый скафандр шахтёра
  description: Шлем шахтёра в магматитовой обёртке.
  components:
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/Equipment/MagmaSuit/salvage.rsi
    layers:
    - state: icon
    - state: icon-lava
      shader: unshaded
    - state: icon-flash
    - state: icon-lava
      visible: false
      shader: unshaded
      map: [ "light" ]
  - type: ToggleableLightVisuals
    spriteLayer: light
    clothingVisuals:
      head:
      - state: on-equipped-HELMET
      - state: equipped-HELMET-lava
        shader: unshaded
      head-reptilian:
      - state: on-equipped-HELMET-reptilian
      - state: equipped-HELMET-lava
        shader: unshaded
  - type: Clothing
    sprite: Adventure/Roles/LavaLand/Equipment/MagmaSuit/salvage.rsi
    clothingVisuals:
      head:
      - state: off-equipped-HELMET
      - state: equipped-HELMET-lava
        shader: unshaded
      head-reptilian:
      - state: off-equipped-HELMET-reptilian
      - state: equipped-HELMET-lava
        shader: unshaded
  - type: PointLight
    color: "#fda144" 
    radius: 9
    energy: 5

# крафт
- type: constructionGraph
  id: HardsuitMagmaSalvage
  start: start
  graph:
  - node: start
    edges:
    - to: hardsuitmagmasalvage
      steps:
      - tag: HardsuitSalvage
        icon:
          sprite: Clothing/OuterClothing/Hardsuits/salvage.rsi
          state: icon
        name: mining hardsuit
        doAfter: 10
      - material: Durathread
        amount: 10
        doAfter: 10
      - material: Magmatite
        amount: 5
        doAfter: 10
  - node: hardsuitmagmasalvage
    entity: ClothingOuterHardsuitMagmaSalvage

- type: construction
  name: магматитовый скафандр шахтёра
  id: HardsuitMagmaSalvage
  graph: HardsuitMagmaSalvage
  startNode: start
  targetNode: hardsuitmagmasalvage
  category: construction-category-clothing
  objectType: Item
  description: Скафандр шахтёра, укреплённый магматитовой рудой.
  icon:
    sprite: Adventure/Roles/LavaLand/Equipment/MagmaSuit/suit.rsi
    state: icon