#База жуков
- type: entity
  abstract: true
  parent: [ SimpleMobBase, MobCombat ]
  id: BaseMobInsectSwarm
  components:
  - type: Sharp
  - type: NpcFactionMember
    factions:
    - Xeno
  - type: HTN
    rootTask:
      task: XenoCompound
    blackboard:
      NavClimb: !type:Bool
        true
      NavInteract: !type:Bool
        true
      NavPry: !type:Bool
        true
      NavSmash: !type:Bool
        true
  - type: Prying 
    pryPowered: true
    force: true
    speedModifier: 1.5
    useSound:
      path: /Audio/Items/crowbar.ogg
  - type: NoSlip
  - type: CombatMode
  - type: MobState
    allowedStates:
    - Alive
    - Dead
  - type: DamageStateVisuals
    states:
      Alive:
        Base: alive
      Dead:
        Base: dead
  - type: Access
    tags:
    - HungerSwarmAccess
  - type: TriggerOnMobstateChange
    mobState:
    - Dead
  - type: EmitSoundOnTrigger
    sound:
      path: /Audio/Adventure/Hungry_Swarm/insect_dead.ogg
      params:
        volume: -2
  - type: Damageable
    damageModifierSet: HungerSwarm
  - type: Speech
    speechVerb: LargeMob
    speechSounds: HungerSwarmSpeech
  - type: EmitSoundOnSpawn
    sound:
      path: /Audio/Adventure/Hungry_Swarm/insect_speech.ogg
      params:
        volume: -8
  - type: IntrinsicRadioReceiver
    channels:
      - HungerSwarm
  - type: IntrinsicRadioTransmitter
    channels:
      - HungerSwarm
  - type: ActiveRadio
    channels:
      - HungerSwarm
  - type: Puller
    needsHands: false
  - type: MeleeWeapon
    altDisarm: false
    angle: 0
    damage:
      types:
        Piercing: 8
        Structural: 30
    soundHit:
     path: /Audio/Adventure/Hungry_Swarm/insect_attack.ogg
    animation: WeaponArcClaw
  - type: Hands
  - type: ComplexInteraction
  - type: Tag
    tags:
    - FootstepSound
    - DoorBumpOpener
    - HungerSwarm
  - type: Hunger 
    thresholds:
      Overfed: 35
      Okay: 25
      Peckish: 15
      Starving: 10
      Dead: 0
    baseDecayRate: 0.050
  - type: Bloodstream
    bloodReagent: InsectBlood
  - type: Devourer
    devourAction: ActionDevourHungerSwarm
    soundDevour: /Audio/Adventure/Hungry_Swarm/insect_eat.ogg
    soundStructureDevour: /Audio/Adventure/Hungry_Swarm/insect_eat.ogg
    foodPreference: All
    shouldStoreDevoured: true
    chemical: UncookedAnimalProteins
    healRate: 10
    devourTime: 5
    whitelist:
      components:
      - Item
  - type: TypingIndicator
    proto: default
  - type: StatusEffects
    allowed:
    - Stun
    - SlowedDown
    - Stutter
    - Electrocution
    - ForcedSleep
    - TemporaryBlindness
    - Pacified
    - RadiationProtection
    - Drowsiness
    - Adrenaline
  - type: PassiveDamage
    allowedStates:
    - Alive
    damageCap: 1000
    damage:
      groups:
        Brute: -1.50
        Burn: -1.50
        Airloss: -1.50
        Toxin: -1.50
        Genetic: -1.50

#Тэг
- type: Tag
  id: HungerSwarm

#Радио 
- type: radioChannel
  id: HungerSwarm
  name: Коллективный разум 
  keycode: 'у'
  frequency: 426
  color: "#d2af52"
  longRange: true

#Броня 
- type: damageModifierSet
  id: HungerSwarm
  coefficients:
    Blunt: 0.95
    Slash: 0.85
    Piercing: 0.70
    Heat: 1.5

# Доступ
- type: accessLevel
  id: HungerSwarmAccess
  name: Возможность использовать постройки.

# Речь
- type: speechSounds
  id: HungerSwarmSpeech
  saySound:
    path: /Audio/Adventure/Hungry_Swarm/insect_speech.ogg
  askSound:
    path: /Audio/Adventure/Hungry_Swarm/insect_speech.ogg
  exclaimSound:
    path: /Audio/Adventure/Hungry_Swarm/insect_speech.ogg