- type: entity
  id: SpawnPointGhostInsectReaperQueen
  name: Гост роль матка улья
  suffix: BORK (HungerSwarm)
  parent: MarkerBase
  components:
  - type: GhostRole
    name: Матка улья
    description: Размножайтесь и поедайте всё, что найдёте.
    rules: Вы [color=red][bold]Командный антагонист[/bold][/color], в команде с другими членами улья.
    mindRoles:
    - MindRoleGhostRoleFreeAgent
    raffle:
      settings: default
  - type: GhostRoleMobSpawner
    prototype: MobInsectReaperQueen
  - type: Sprite
    sprite: Markers/jobs.rsi
    layers:
      - state: green
      - sprite: Adventure/Roles/Hungry_Swarm/queen.rsi
        state: icon

- type: entity
  id: HungerSwarmInvasion
  parent: BaseStationEventShortDelay
  components:
  - type: StationEvent
    earliestStart: 25
    weight: 6.5
    duration: null
    minimumPlayers: 30 
  - type: SpaceSpawnRule
    spawnDistance: 0
  - type: AntagSpawner
    prototype: MobInsectReaperQueen
  - type: AntagSelection
    definitions:
    - spawnerPrototype: SpawnPointGhostInsectReaperQueen
      min: 1
      max: 1
      pickPlayer: false