#Жнец
- type: entity
  name: жнец
  suffix: BORK (HungerSwarm)
  description: Им движет только одно - сожрать вас.
  parent: [ BaseMobInsectSwarm, FlyingMobBase ]
  id: MobInsectReaper
  components:
  - type: Sprite
    drawdepth: Mobs
    sprite: Adventure/Roles/Hungry_Swarm/reaper.rsi
    layers:
    - map: ["enum.DamageStateVisualLayers.Base"]
      state: alive
  - type: MobThresholds
    thresholds:
      0: Alive
      100: Dead
  - type: SlowOnDamage
    speedModifierThresholds:
      70: 0.7
  - type: MovementSpeedModifier
    baseSprintSpeed: 5
    baseWalkSpeed : 5.5
  - type: GhostRole
    allowMovement: true
    allowSpeech: true
    makeSentient: true
    name: Жнец улья
    description: Размножайтесь и поедайте всё, что найдёте.
    rules: Вы [color=red][bold]Командный антагонист[/bold][/color], в команде с другими членами улья.
    raffle:
      settings: short
  - type: GhostTakeoverAvailable
  - type: Butcherable
    spawned:
      - id: FoodMeat
        amount: 1
  - type: FootstepModifier
    footstepSoundCollection:
      collection: ReaperFly
      params: 
        volume: -10
  - type: Spider
    webPrototype: HungerSwarmWeb
    webAction: ActionHungerSwarmWeb
  - type: EggLayer
    hungerUsage: 15
    eggLayAction: ActionHungerSwarmLayEgg
    eggLaySound: !type:SoundPathSpecifier
      path: /Audio/Adventure/Hungry_Swarm/insect_dead.ogg
    eggSpawn:
    - id: InsectReaperEgg
  - type: PointLight
    radius: 2
    energy: 2
    color: "#d2af52"
  - type: ActionGun
    action: ActionReaperSting
    gunProto: ReaperGun
  - type: AutoImplant
    implants:
    - ActionHungerSwarmWallImplant  
    - ActionHungerSwarmDoorImplant
    - ActionHungerSwarmWebLightImplant

- type: soundCollection
  id: ReaperFly
  files:
  - /Audio/Adventure/Hungry_Swarm/insect_fly1.ogg
  - /Audio/Adventure/Hungry_Swarm/insect_fly2.ogg
  - /Audio/Adventure/Hungry_Swarm/insect_fly3.ogg

#Личинка жнеца
- type: entity
  name: личинка жнеца
  suffix: BORK (HungerSwarm)
  description: Им движет только одно - сожрать вас.
  parent: BaseMobInsectSwarm
  id: MobInsectLarva
  components:
  - type: Sprite
    drawdepth: Mobs
    sprite: Adventure/Roles/Hungry_Swarm/larva.rsi
    layers:
    - map: ["enum.DamageStateVisualLayers.Base"]
      state: alive
  - type: MobThresholds
    thresholds:
      0: Alive
      50: Dead
  - type: SlowOnDamage
    speedModifierThresholds:
      70: 0.7
  - type: MovementSpeedModifier
    baseSprintSpeed: 2
    baseWalkSpeed : 2.5
  - type: GhostRole
    allowMovement: true
    allowSpeech: true
    makeSentient: true
    name: Личинка жнеца
    description: Дождитесь взросления и помогите рою выжить.
    rules: Вы [color=red][bold]Командный антагонист[/bold][/color], в команде с другими членами улья.
    raffle:
      settings: short
  - type: GhostTakeoverAvailable
  - type: Butcherable
    spawned:
      - id: FoodMeat
        amount: 1
  - type: FootstepModifier
    footstepSoundCollection:
      collection: LarvaRun
      params: 
        volume: -10
  - type: Reform
    actionPrototype: ReaperEvolutionAction
    reformTime: 20
    popupText: Вы начинаете окукливаться и отращивать крылья
    reformPrototype: MobInsectReaper

- type: soundCollection
  id: LarvaRun
  files:
  - /Audio/Adventure/Hungry_Swarm/larva_run1.ogg
  - /Audio/Adventure/Hungry_Swarm/larva_run2.ogg

#яйца 
- type: entity
  id: InsectReaperEgg
  parent: BaseItem
  description: Там что-то швелится.
  name: яйцо жнеца
  suffix: BORK (HungerSwarm)
  components:
  - type: Item
    size: Huge
  - type: Damageable
    damageContainer: Biological
  - type: Sprite
    sprite: Adventure/Roles/Hungry_Swarm/other.rsi
    state: egg
  - type: Timer
  - type: TimedSpawner
    prototypes:
    - MobInsectLarva
    intervalSeconds: 120
    minimumEntitiesSpawned: 1
    maximumEntitiesSpawned: 1
  - type: TimedDespawn
    lifetime: 121
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 100
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: desecration
      - !type:SpillBehavior
        solution: food
      - !type:SpawnEntitiesBehavior
        spawn:
          MobInsectLarva:
            min: 1
            max: 1
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: DamageOnHighSpeedImpact
    minimumSpeed: 0.1
    damage:
      types:
        Blunt: 1

#жало
- type: entity
  id: BulletReaperSting
  name: жало жнеца
  parent: BaseBullet
  noSpawn: true
  components:
    - type: Sprite
      noRot: false
      sprite: Adventure/Roles/Hungry_Swarm/other.rsi
      layers:
        - state: sting
    - type: EmitSoundOnSpawn
      sound:
        path: /Audio/Adventure/Hungry_Swarm/insect_attack.ogg
    - type: Projectile
      impactEffect: BulletImpactEffectKinetic
      damage:
        types:
          Slash: 5
          Piercing: 5

- type: entity
  noSpawn: true
  id: ReaperGun
  components:
  - type: RechargeBasicEntityAmmo
    rechargeCooldown: 5
  - type: BasicEntityAmmoProvider
    proto: BulletReaperSting
    capacity: 1
    count: 1
  - type: Gun
    soundGunshot:
      path: /Audio/Adventure/Hungry_Swarm/insect_attack.ogg
    projectileSpeed: 10