# кароче, благодаря этому жнецы помещаются в канале связи роя как часть рой, а не как нонэймы...
- type: department
  id: HungerSwarm
  name: Рой
  description: Поглотите всё живое.
  color: "#ffd566"
  roles:
  - HungerSwarm
  editorHidden: true

- type: jobIcon
  parent: JobIcon
  id: JobIconHungerSwarm
  icon:
    sprite: /Textures/Interface/Misc/job_icons.rsi
    state: Unknown
  jobName: Рой

- type: playTimeTracker
  id: HungerSwarm

- type: job
  id: HungerSwarm
  name: Рой
  description: Ещё те твари.
  icon: "JobIconHungerSwarm"
  playTimeTracker: HungerSwarm
  setPreference: false
  startingGear: HungerSwarm
  supervisors: Коллективу роя.
  access:
  - HungerSwarmAccess

- type: entity
  parent: IDCardStandard
  id: HungerSwarmID
  categories: [ HideSpawnMenu ]
  description: Нейронная связь позволяет проходам ульяраспозновать вас как часть роя.
  name: нейронная связь
  components:
  - type: Sprite
    sprite: Adventure/Roles/Hungry_Swarm/other.rsi
    layers:
    - state: neiro
  - type: Item
  - type: PresetIdCard
    job: HungerSwarm
  - type: Unremoveable

- type: inventoryTemplate
  id: HungerSwarm
  slots:
    - name: id
      slotTexture: id
      fullTextureName: template_small
      slotFlags: IDCARD
      slotGroup: SecondHotbar
      stripTime: 6
      uiWindowPos: 2,1
      strippingWindowPos: 2,4
      displayName: ID
    - name: pocket1
      slotTexture: pocket
      slotFlags: POCKET
      slotGroup: MainHotbar
      stripTime: 3
      uiWindowPos: 0,3
      strippingWindowPos: 0,4
      displayName: Pocket 1
      stripHidden: true

- type: startingGear
  id: HungerSwarm
  equipment:
    id: HungerSwarmID
    pocket1: PinpointerHungerSwarm

#чутьё улья
- type: entity
  name: чутьё улья
  description: Вы можете чувствовать ближайшую станцию для постройки улья.
  parent: BaseItem
  categories: [ HideSpawnMenu ]
  id: PinpointerHungerSwarm
  components:
  - type: Unremoveable
  - type: Transform
    noRot: True
  - type: Sprite
    noRot: True
    sprite: Adventure/Roles/Hungry_Swarm/pin.rsi
    layers:
    - state: pin
      map: ["enum.PinpointerLayers.Base"]
    - state: pinonnull
      map: ["enum.PinpointerLayers.Screen"]
      shader: unshaded
      visible: false
  - type: Icon
    sprite: Adventure/Roles/Hungry_Swarm/pin.rsi
    state: pin
  - type: Item
    sprite: Adventure/Roles/Hungry_Swarm/pin.rsi
  - type: Appearance
  - type: GenericVisualizer
    visuals:
      enum.PinpointerVisuals.IsActive:
        enum.PinpointerLayers.Screen:
          True: { visible: True }
          False: { visible: False }
      enum.PinpointerVisuals.TargetDistance:
        enum.PinpointerLayers.Screen:
          Unknown: { state: pinonnull }
          Reached: { state: pinondirect }
          Close: { state: pinonclose }
          Medium: { state: pinonmedium }
          Far: { state: pinonfar }
  - type: AnimationPlayer
  - type: Pinpointer
    component: ResearchServer
    targetName: ближайшая станция