# кароче, благодаря этому жнецы помещаются в канале связи роя как часть рой, а не как нонэймы...
- type: department
  id: HungerSwarm
  name: Рой
  description: Поглотите всё живое.
  color: "#ffd566"
  roles:
  - HungerSwarm
  editorHidden: true

- type: jobIcon
  parent: JobIcon
  id: JobIconHungerSwarm
  icon:
    sprite: /Textures/Interface/Misc/job_icons.rsi
    state: Unknown
  jobName: Рой

- type: playTimeTracker
  id: HungerSwarm

- type: job
  id: HungerSwarm
  name: Рой
  description: Ещё те твари.
  icon: "JobIconHungerSwarm"
  playTimeTracker: HungerSwarm
  setPreference: false
  startingGear: HungerSwarm
  supervisors: Коллективу роя.
  access:
  - HungerSwarmAccess

- type: entity
  parent: IDCardStandard
  id: HungerSwarmID
  description: Нейронная связь позволяет проходам ульяраспозновать вас как часть роя.
  name: нейронная связь
  components:
  - type: Sprite
    sprite: Adventure/Roles/Hungry_Swarm/other.rsi
    layers:
    - state: neiro
  - type: Item
  - type: PresetIdCard
    job: HungerSwarm
  - type: Unremoveable

- type: inventoryTemplate
  id: HungerSwarm
  slots:
    - name: id
      slotTexture: id
      fullTextureName: template_small
      slotFlags: IDCARD
      slotGroup: SecondHotbar
      stripTime: 6
      uiWindowPos: 2,1
      strippingWindowPos: 2,4
      displayName: ID

- type: startingGear
  id: HungerSwarm
  equipment:
    id: HungerSwarmID