#изумруд
- type: entity
  parent: MaterialBase
  id: Emerald
  name: изумруд
  description: Обработанный драгоценный камень.
  suffix: LavaLand
  components:
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/materials/gems.rsi
    layers:
    - state: Emerald
  - type: Appearance
  - type: Stack
    stackType: Emerald
  - type: Material
  - type: PhysicalComposition
    materialComposition:
      ProcessedEmerald: 100

- type: latheRecipe
  id: Emerald
  result: Emerald1
  completetime: 0
  materials:
    RawEmerald: 400

- type: entity
  parent: Emerald
  id: Emerald1
  suffix: 1
  components:
  - type: Stack
    count: 1

- type: stack
  id: Emerald
  name: изумруд
  icon: { sprite: /Textures/Adventure/Roles/LavaLand/materials/gems.rsi, state: Emerald }
  spawn: Emerald1
  maxCount: 30

- type: material
  id: ProcessedEmerald
  name: изумруд
  unit: materials-unit-piece
  icon: { sprite: Adventure/Roles/LavaLand/materials/gems.rsi, state: Emerald }
  color: "#2ad75a"
  price: 12

#рубин
- type: entity
  parent: MaterialBase
  id: Ruby
  name: рубин
  description: Обработанный драгоценный камень.
  suffix: LavaLand
  components:
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/materials/gems.rsi
    layers:
    - state: Ruby
  - type: Appearance
  - type: Stack
    stackType: Ruby
  - type: Material
  - type: PhysicalComposition
    materialComposition:
      ProcessedRuby: 100

- type: latheRecipe
  id: Ruby
  result: Ruby1
  completetime: 0
  materials:
    RawRuby: 400

- type: entity
  parent: Ruby
  id: Ruby1
  suffix: 1
  components:
  - type: Stack
    count: 1

- type: stack
  id: Ruby
  name: рубин
  icon: { sprite: /Textures/Adventure/Roles/LavaLand/materials/gems.rsi, state: Ruby }
  spawn: Ruby1
  maxCount: 30

- type: material
  id: ProcessedRuby
  name: рубин
  unit: materials-unit-piece
  icon: { sprite: Adventure/Roles/LavaLand/materials/gems.rsi, state: Ruby }
  color: "#f24646"
  price: 10

#сапфир
- type: entity
  parent: MaterialBase
  id: Sapphire
  name: сапфир
  description: Обработанный драгоценный камень.
  suffix: LavaLand
  components:
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/materials/gems.rsi
    layers:
    - state: Sapphire
  - type: Appearance
  - type: Stack
    stackType: Sapphire
  - type: Material
  - type: PhysicalComposition
    materialComposition:
      ProcessedSapphire: 100

- type: latheRecipe
  id: Sapphire
  result: Sapphire1
  completetime: 0
  materials:
    RawSapphire: 400

- type: entity
  parent: Sapphire
  id: Sapphire1
  suffix: 1
  components:
  - type: Stack
    count: 1

- type: stack
  id: Sapphire
  name: сапфир
  icon: { sprite: /Textures/Adventure/Roles/LavaLand/materials/gems.rsi, state: Sapphire }
  spawn: Sapphire1
  maxCount: 30

- type: material
  id: ProcessedSapphire
  name: сапфир
  unit: materials-unit-piece
  icon: { sprite: Adventure/Roles/LavaLand/materials/gems.rsi, state: Sapphire }
  color: "#305de4"
  price: 8

#топаз
- type: entity
  parent: MaterialBase
  id: Topaz
  name: топаз
  description: Обработанный драгоценный камень.
  suffix: LavaLand
  components:
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/materials/gems.rsi
    layers:
    - state: Topaz
  - type: Appearance
  - type: Stack
    stackType: Topaz
  - type: Material
  - type: PhysicalComposition
    materialComposition:
      ProcessedTopaz: 100

- type: latheRecipe
  id: Topaz
  result: Topaz1
  completetime: 0
  materials:
    RawTopaz: 400

- type: entity
  parent: Topaz
  id: Topaz1
  suffix: 1
  components:
  - type: Stack
    count: 1

- type: stack
  id: Topaz
  name: топаз
  icon: { sprite: /Textures/Adventure/Roles/LavaLand/materials/gems.rsi, state: Topaz }
  spawn: Topaz1
  maxCount: 30

- type: material
  id: ProcessedTopaz
  name: топаз
  unit: materials-unit-piece
  icon: { sprite: Adventure/Roles/LavaLand/materials/gems.rsi, state: Topaz }
  color: "#f29d46"
  price: 15

#драконий рубин
- type: entity
  parent: MaterialBase
  id: DragonRuby
  name: драконий рубин
  description: Обработанный драгоценный камень из пламени дракона.
  suffix: LavaLand
  components:
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/materials/gems.rsi
    layers:
    - state: Dragon_stone
  - type: Appearance
  - type: Stack
    stackType: DragonRuby
    count: 10
  - type: Material
  - type: PhysicalComposition
    materialComposition:
      ProcessedDragonRuby: 100
  - type: PointLight
    radius: 2
    energy: 1.5
    color: "#ee5858"

- type: latheRecipe
  id: DragonRuby
  result: DragonRuby1
  completetime: 0
  materials:
    RawDragon: 1000

- type: entity
  parent: DragonRuby
  id: DragonRuby1
  suffix: 1
  components:
  - type: Stack
    count: 1

- type: stack
  id: DragonRuby
  name: драконий рубин
  icon: { sprite: /Textures/Adventure/Roles/LavaLand/materials/gems.rsi, state: Dragon_stone }
  spawn: Emerald1
  maxCount: 10

- type: material
  id: ProcessedDragonRuby
  name: драконий рубин
  unit: materials-unit-piece
  icon: { sprite: Adventure/Roles/LavaLand/materials/gems.rsi, state: Dragon_stone }
  color: "#ee5858"
  price: 80

#бароксульдий
- type: entity
  parent: MaterialBase
  id: Phoron
  name: бароксульдий
  description: Обработанный драгоценный камень.
  suffix: LavaLand
  components:
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/materials/gems.rsi
    layers:
    - state: Phoron
  - type: Appearance
  - type: Stack
    stackType: Phoron
  - type: Material
  - type: PhysicalComposition
    materialComposition:
      ProcessedPhoron: 100
  - type: PointLight
    radius: 2
    energy: 1.5
    color: "#cb5ee5"

- type: latheRecipe
  id: Phoron
  result: Phoron1
  completetime: 0
  materials:
    RawPharo: 200

- type: entity
  parent: Phoron
  id: Phoron1
  suffix: 1
  components:
  - type: Stack
    count: 1

- type: stack
  id: Phoron
  name: бароксульдий
  icon: { sprite: /Textures/Adventure/Roles/LavaLand/materials/gems.rsi, state: Phoron }
  spawn: Phoron1
  maxCount: 30

- type: material
  id: ProcessedPhoron
  name: бароксульдий
  unit: materials-unit-piece
  icon: { sprite: Adventure/Roles/LavaLand/materials/gems.rsi, state: Phoron }
  color: "#cb5ee5"
  price: 30

#рупериум
- type: entity
  parent: MaterialBase
  id: Rupee
  name: рупериум
  description: Обработанный драгоценный камень.
  suffix: LavaLand
  components:
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/materials/gems.rsi
    layers:
    - state: Rupee
  - type: Appearance
  - type: Stack
    stackType: Rupee
  - type: Material
  - type: PhysicalComposition
    materialComposition:
      ProcessedRupee: 100

- type: latheRecipe
  id: Rupee
  result: Rupee1
  completetime: 0
  materials:
    RawRupee: 800

- type: entity
  parent: Rupee
  id: Rupee1
  suffix: 1
  components:
  - type: Stack
    count: 1

- type: stack
  id: Rupee
  name: рупериум
  icon: { sprite: /Textures/Adventure/Roles/LavaLand/materials/gems.rsi, state: Rupee }
  spawn: Rupee1
  maxCount: 30

- type: material
  id: ProcessedRupee
  name: рупериум
  unit: materials-unit-piece
  icon: { sprite: Adventure/Roles/LavaLand/materials/gems.rsi, state: Rupee }
  color: "#d6fe36"
  price: 30

- type: entity
  id: WallRockBasaltGoldWarm
  name: базальт
  description: Рудная жила, богатая золотом.
  parent: WallRockBasaltGold
  suffix: рудожор LavaLand
  components:
    - type: OreVein
      oreChance: 1.0
      currentOre: OreGoldWarm

- type: ore
  id: OreGoldWarm
  oreEntity: MobLavaLandGoldWarm