- type: entity
  id: OldChestRandomLoot
  suffix: Рандомный лут LavaLand
  parent: OldChest
  components:
  - type: Transform
    anchored: true
  - type: StorageFill
    contents:
      - id: OreDragon1
        amount: 1
        prob: 0.2
      - id: OrganFelinidHeart
        prob: 0.2
      - id: ClothingShoesCult
        prob: 0.5
      - id: RitualDagger
        amount: 2
        prob: 0.3
      - id: ClothingHeadHatHoodCulthood
        amount: 2
        prob: 0.5
      - id: SpawnSpellbook
        amount: 1
        prob: 0.2
      - id: ClothingOuterArmorPodWars
        amount: 1
        prob: 0.3
      - id: ClothingOuterRobesCult
        amount: 1
        prob: 0.5
      - id: Ointment1
        amount: 2
        prob: 0.3
      - id: Ointment1
        amount: 1
        prob: 0.3
      - id: Brutepack1
        amount: 2
        prob: 0.3
      - id: Brutepack1
        amount: 1
        prob: 0.3
      - id: GoldenAppleSeeds
        amount: 1
        prob: 0.2
      - id: Ointment
        amount: 1
        prob: 0.1
      - id: Brutepack
        amount: 1
        prob: 0.1
      - id: IngotGold1
        amount: 3
        prob: 0.2
      - id: IngotGold1
        amount: 2
        prob: 0.2
      - id: IngotGold1
        amount: 1
        prob: 0.2
      - id: IngotSilver1
        amount: 3
        prob: 0.2
      - id: IngotSilver1
        amount: 2
        prob: 0.2
      - id: IngotSilver1
        amount: 1
        prob: 0.2
      - id: CentCommCrystal1
        amount: 2
        prob: 0.2
      - id: Telecrystal1
        amount: 2
        prob: 0.2
      - id: Telecrystal1
        amount: 1
        prob: 0.2
      - id: ShardCrystalGreen
        amount: 1
        prob: 0.3
      - id: WeaponCrusherGlaive
        amount: 1
        prob: 0.05
      - id: MiningDrillDiamond
        amount: 1
        prob: 0.05