- type: entity
  id: BorgCuffed
  name: Заковать
  description: Заковать нарушителя стяжками.
  categories: [ HideSpawnMenu ]
  components:
  - type: EntityTargetAction
    icon: { sprite: Adventure/Roles/BorgDep/SecBorg/modul.rsi, state: SecBorgCuff }
    itemIconStyle: NoItem
    whitelist:
      components:
      - Cuffable
    canTargetSelf: false
    useDelay: 15
    checkCanAccess: true
    range: 2
    event: !type:BorgCuffedActionEvent
    priority: 9