- type: reagent
  id: FleshMass
  name: Биомасса плоти
  group: Toxins
  desc: Какая-то грязь
  flavor: bitter
  color: "#ab2b52"
  physicalDesc: мерзкое
  metabolisms:
    Poison:
      metabolismRate: 0.05
      effects:
        - !type:HealthChange
          damage:
            types:
              Poison: 0

- type: reagent
  id: FleshMassKaBoom
  name: Биомасса плоти
  group: Toxins
  desc: Какая-то грязь
  flavor: bitter
  color: "#ab2b52"
  physicalDesc: мерзкое
  metabolisms:
    Poison:
      metabolismRate: 1
      effects:
        - !type:HealthChange
          damage:
            types:
              Blunt: 10000    

- type: reagent
  id: FleshMassFleshKudzu
  name: Биомасса плоти
  group: Toxins
  desc: Какая-то грязь
  flavor: bitter
  color: "#ab2b52"
  physicalDesc: мерзкое
  metabolisms:
    Poison:
      metabolismRate: 0.05
      effects:
        - !type:HealthChange
          damage:
            types:
              Poison: 0          

- type: reaction
  id: FleshMassGib
  quantized: true
  reactants:
    FleshMass:
      amount: 0.1
    UncookedAnimalProteins:
      amount: 55
  effects:
  - !type:CreateGas
    gas: Ammonia
  - !type:PopupMessage
    visualType: LargeCaution
    messages: [ "Избыточная масса вырывается наружу." ]
    type: Pvs
  products:
    FleshMassKaBoom: 1
    FleshMassFleshKudzu: 10

- type: reaction
  id: FleshKudzuFleshMass
  quantized: true
  reactants:
    FleshMassFleshKudzu:
      amount: 5
    Blood:
      amount: 5
  effects:
  - !type:CreateEntityReactionEffect
    entity: FleshKudzu
  - !type:PopupMessage
    visualType: LargeCaution
    messages: [ "Сухожилия вырываются наружу." ]
    type: Pvs