- type: body
  id: FleshHuman
  name: "human"
  root: torso
  slots:
    head:
      part: HeadHuman
      connections:
      - torso
      organs:
        brain: FleshOrganBrain
        eyes: FleshOrganEyeball
    torso:
      part: TorsoHuman
      connections:
      - right_arm
      - left_arm
      - right_leg
      - left_leg
      organs:
        heart: FleshOrganHeart
        lungs: FleshOrganLung
        stomach: FleshOrganStomach
        liver: FleshOrganLiver
        kidneys: FleshOrganKidney
    right_arm:
      part: RightArmHuman
      connections:
      - right_hand
    left_arm:
      part: LeftArmHuman
      connections:
      - left_hand
    right_hand:
      part: RightHandHuman
    left_hand:
      part: LeftHandHuman
    right_leg:
      part: RightLegHuman
      connections:
      - right_foot
    left_leg:
      part: LeftLegHuman
      connections:
      - left_foot
    right_foot:
      part: RightFootHuman
    left_foot:
      part: LeftFootHuman

- type: entity
  parent: MobHuman
  id: MobHumanFlesh
  name: человек плоти
  components:
  - type: SolutionContainerManager
    solutions:
      chemicals:
        reagents:
        - ReagentId: FleshMass
          Quantity: 20
  - type: SolutionRegeneration
    solution: chemicals
    generated:
      reagents:
      - ReagentId: FleshMass
        Quantity: 0.05
  - type: Prying
    pryPowered: true
    force: true
    speedModifier: 1.5
    useSound:
      path: /Audio/Items/crowbar.ogg
  - type: Hunger
    baseDecayRate: 0.0864
  - type: Body
    prototype: FleshHuman
  - type: RandomHumanoidAppearance
    randomizeName: true
  - type: IntrinsicRadioReceiver
  - type: IntrinsicRadioTransmitter
    channels:
    - Flesh
  - type: ActiveRadio
    channels:
    - Flesh
  - type: NpcFactionMember
    factions:
    - SimpleHostile
  - type: Tag
    tags:
    - CanPilot
    - FootstepSound
    - DoorBumpOpener
    - Flesh
  - type: Spider
    webPrototype: FleshWeb
    webAction: ActionFleshWeb
  - type: GibAction
    actionPrototype: FleshBreakAction
    allowedStates:
    - Critical
    - Dead
  - type: Devourer
    devourAction: ActionDevourFlesh
    foodPreference: All
    shouldStoreDevoured: true
    chemical: UncookedAnimalProteins
    healRate: 30
    devourTime: 10
    whitelist:
      components:
      - Bloodstream
  - type: Sericulture
    action: ActionSpawnFleshSpawners
    productionLength: 8
    entityProduced: FleshSpawner
    hungerCost: 50

#Поглотить
- type: entity
  id: ActionDevourFlesh
  name: "[color=red]Поглотить[/color]"
  description: Вас одолевает голод, время его утолить.
  noSpawn: true
  components:
  - type: EntityTargetAction
    icon: { sprite : Interface/Actions/devour.rsi, state: icon }
    iconOn: { sprite : Interface/Actions/devour.rsi, state: icon-on }
    event: !type:DevourActionEvent
    priority: 1