- type: htnCompound
  id: SimpleMeleeRangedHostileCompoundAudioTrigger
  branches:
    - tasks:
        - !type:HTNCompoundTask
          task: MeleeRangedCombatCompound
    - tasks:
        - !type:HTNPrimitiveTask
          operator: !type:UtilityOperator
            proto: NearbyGunTargets
        - !type:HTNPrimitiveTask
          preconditions:
            - !type:KeyExistsPrecondition
              key: Target
            - !type:TargetInLOSPrecondition
              targetKey: Target
              rangeKey: RangedRange
          operator: !type:GunOperator
            targetKey: Target
            requireLOS: true
          services:
            - !type:UtilityService
              id: RangedService
              proto: NearbyGunTargets
              key: Target
    - tasks:
        - !type:HTNCompoundTask
          task: IdleCompound

- type: htnCompound
  id: MeleeRangedCombatCompound
  branches:
    - preconditions:
        - !type:GunAmmoPrecondition
          minPercent: 0.001
      tasks:
        - !type:HTNCompoundTask
          task: GunCombatCompoundNostepBack
    - tasks:
        - !type:HTNPrimitiveTask
          operator: !type:UtilityOperator
            proto: NearbyMeleeTargets
        - !type:HTNCompoundTask
          task: BeforeMeleeAttackTargetCompound

- type: htnCompound
  id: GunCombatCompoundNostepBack
  branches:
    - tasks:
        - !type:HTNPrimitiveTask
          operator: !type:UtilityOperator
            proto: NearbyGunTargets

        - !type:HTNPrimitiveTask
          operator: !type:MoveToOperator
            shutdownState: PlanFinished
            pathfindInPlanning: true
            removeKeyOnFinish: true
            targetKey: TargetCoordinates
            pathfindKey: TargetPathfind
            stopOnLineOfSight: false
            rangeKey: MeleeRange

        - !type:HTNPrimitiveTask
          operator: !type:JukeOperator
            jukeType: AdjacentTile

        - !type:HTNPrimitiveTask
          preconditions:
            - !type:KeyExistsPrecondition
              key: Target
          operator: !type:GunOperator
            targetKey: Target
          services:
            - !type:UtilityService
              id: RangedService
              proto: NearbyGunTargets
              key: Target