- type: dungeonConfig
  id: AdventureLava
  layers:
    - !type:PrototypeDunGen
      proto: LavaBlob
    - !type:PrototypeDunGen
      proto: LavaSmallPaths
#Rooms
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker1
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker2
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker3
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker4
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker5
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker6
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker7
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker8
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker9
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker10
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker11
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker12
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker13
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker14
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker15
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker16
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker17
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker18
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker19
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker20
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker21
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker22
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker23
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker24
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker25
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker26
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker27
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker28
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker29
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker30
#Rooms
    - !type:PrototypeDunGen
      proto: LavaFill
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltBananium
      count: 20
      minGroupSize: 3
      maxGroupSize: 8
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltTin
      count: 35
      minGroupSize: 8
      maxGroupSize: 12
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltCoal
      count: 35
      minGroupSize: 8
      maxGroupSize: 12
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltQuartz
      count: 35
      minGroupSize: 10
      maxGroupSize: 15
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltSalt
      count: 35
      minGroupSize: 8
      maxGroupSize: 12
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltGold
      count: 35
      minGroupSize: 8
      maxGroupSize: 12
    - !type:OreDunGen
      replacement: WallRockBasaltGold
      entity: WallRockBasaltGoldWarm
      count: 20
      minGroupSize: 2
      maxGroupSize: 5
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltSilver
      count: 35
      minGroupSize: 8
      maxGroupSize: 12
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltPlasma
      count: 35
      minGroupSize: 4
      maxGroupSize: 8
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltUranium
      count: 35
      minGroupSize: 4
      maxGroupSize: 8
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltArtifactFragment
      count: 25
      minGroupSize: 1
      maxGroupSize: 3
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltDiamond
      count: 15
      minGroupSize: 1
      maxGroupSize: 2
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltMagmatite
      count: 25
      minGroupSize: 6
      maxGroupSize: 10
    - !type:OreDunGen
      replacement: WallRockBasaltMagmatite
      entity: WallRockBasaltMagmatiteCrab
      count: 10
      minGroupSize: 2
      maxGroupSize: 5
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltGem
      count: 15
      minGroupSize: 3
      maxGroupSize: 6
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: FloorLavaEntity
      count: 350
      minGroupSize: 3
      maxGroupSize: 15
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: BasaltRandom
      count: 350
      minGroupSize: 3
      maxGroupSize: 10
    - !type:OreDunGen
      replacement: FloorLavaEntity
      entity: BasaltRandom
      count: 200
      minGroupSize: 1
      maxGroupSize: 3
    - !type:OreDunGen
      replacement: BasaltRandom
      entity: NecroSpike
      count: 100
      minGroupSize: 1
      maxGroupSize: 1
    - !type:OreDunGen
      replacement: BasaltRandom
      entity: CoalMushroom
      count: 20
      minGroupSize: 1
      maxGroupSize: 3
    - !type:OreDunGen
      replacement: BasaltRandom
      entity: PorciniMushroom
      count: 20
      minGroupSize: 1
      maxGroupSize: 3
    - !type:OreDunGen
      replacement: BasaltRandom
      entity: InocybeMushroom
      count: 20
      minGroupSize: 1
      maxGroupSize: 3
    - !type:OreDunGen
      replacement: BasaltRandom
      entity: PolyporeMushroom
      count: 20
      minGroupSize: 1
      maxGroupSize: 3
    - !type:OreDunGen
      replacement: BasaltRandom
      entity: SpaceCactus
      count: 20
      minGroupSize: 1
      maxGroupSize: 3
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: FloorChasmEntity
      count: 50
      minGroupSize: 3
      maxGroupSize: 10

- type: dungeonConfig
  id: LavaBlob
  layers:
  - !type:NoiseDistanceDunGen
    size: 272, 272
    distanceConfig: !type:DunGenEuclideanSquaredDistance
      blendWeight: 0.80
    layers:
    - tile: FloorBasaltLavaLand
      threshold: 0.50
      noise:
        frequency: 0.010
        noiseType: OpenSimplex2
        fractalType: FBm
        octaves: 5
        lacunarity: 2
        gain: 0.5

- type: dungeonConfig
  id: LavaSmallPaths
  reserveTiles: true
  layers:
  - !type:ReplaceTileDunGen
    layers:
    - tile: FloorBasaltLavaLand
      threshold: 0.75
      noise:
        frequency: 0.040
        noiseType: OpenSimplex2
        fractalType: Ridged
        lacunarity: 1.5
        octaves: 2
        gain: 2.0
  - !type:MobsDunGen
    minCount: 30
    maxCount: 40
    groups:
    - id: SalvageSpawnerMobLavaLand
      amount: 1

- type: dungeonConfig
  id: LavaFill
  data:
    entities:
      Fill: WallRockBasalt
  layers:
  - !type:FillGridDunGen
    allowedTiles:
    - FloorBasaltLavaLand

#спавнеры мобов
- type: entity
  parent: MarkerBase
  id: SalvageSpawnerMobLavaLand
  name: Mining Lava Mob Spawner
  components:
  - type: Sprite
    layers:
    - state: green
    - sprite: Mobs/Aliens/Asteroid/goliath.rsi
      state: goliath
  - type: EntityTableSpawner
    table: !type:GroupSelector
      children:
      - id: MobLavaLandGoliath
        weight: 25
      - id: MobLavaLandGoliathAncient
        weight: 15
      - id: MobWatcherLavaLandFire
        weight: 20
      - id: MobLavaLandLegion
        weight: 30
      - id: MobSkeletonBloodMinerCutter
        weight: 2
      - id: MobSkeletonBloodMinerAccelerator
        weight: 4
      - id: MobSkeletonBloodMinerMiningDrill
        weight: 4

- type: tile
  id: FloorBasaltLavaLand
  parent: FloorBasalt
  name: пол базальт