- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requirements:
  - !type:RoleTimeRequirement
    role: JobScientist
    time: 18000 #5 hrs
  - !type:DepartmentTimeRequirement
    department: Science
    time: 54000 #15 hrs # Adventure
  - !type:AgeRequirement
    requiredAge: 30 # Adventure
# Adventure-edit-start
  - !type:SpeciesRequirement
    inverted: true
    species:
    - Synth
    - Zerah
    - PigMan
    - Vox
# Adventure-edit-end
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    id: RnDPDA
    ears: ClothingHeadsetRD
    ipc: IPCModulEng # Adventure-IPC
  storage:
    back:
    - Flash
