name: Cyrillic Check

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  build:
    name: Cyrillic Check
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.6.0
    - name: Check for cyrillic names in the files
      run: Tools/_Adventure/check_cyrillic.sh
