name: CRLF Check

# c4llv07e disable automatic workflows begin
# on:
#   pull_request:
#     types: [ opened, reopened, synchronize, ready_for_review ]
# c4llv07e disable automatic workflows end

jobs:
  build:
    name: CRLF Check
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.6.0
    - name: Check for CRLF
      run: Tools/check_crlf.py
