name: "Labels: Untriaged"

# c4llv07e disable automatic workflows begin
# on:
#   issues:
#     types: [opened]
# c4llv07e disable automatic workflows end

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      if: join(github.event.issue.labels) == ''
      with:
        labels: "Status: Untriaged"
