name: "Labels: Review"

# c4llv07e disable automatic workflows begin
# on:
#   pull_request_target:
#     types: [review_requested]
# c4llv07e disable automatic workflows end

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "Status: Needs Review"
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: "Status: Awaiting Changes"
